handle: payWithPayPal
isArchived: false
isFrontendEnabled: true
name: 'Pay with PayPal'
paymentType: purchase
settings:
  borderColor: ''
  brandName: NeuroScience
  headerImageUrl: ''
  landingPage: Billing
  logoImageUrl: 'https://www.neuroscienceinc.com/images/general/NeuroScience-logo.png'
  password: MRDMHFJN64L9ZVEV
  sendCartInfo: ''
  signature: AN1Rz6wHNQUyPofH-0WSYGof5rSmAy2WmVHa.FtGjkY2hpT8mx4pZa70
  solutionType: Sole
  testMode: ''
  username: laurie.mceachran_api1.neurorelief.com
sortOrder: 2
type: craft\commerce\paypal\gateways\PayPalExpress
