field: 6a35777e-50b5-46b1-b3e6-294e9553bd87 # Basic Form Fields
fieldLayouts:
  87a6cd5e-7ff2-4974-a1b9-ada96668c420:
    tabs:
      -
        elements:
          -
            fieldUid: 28e0666d-9435-4ecc-a982-159f66e10a7a # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1bc04a61-5ea5-418a-9625-fa2762b6fc12 # Handle
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a690e150-8755-4a1a-b7ff-02574430df1f # Options
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fc8eb0ae-eff2-4677-b3f0-c5af3d8d2a35 # Required
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1bc04a61-5ea5-418a-9625-fa2762b6fc12: # Handle
    columnSuffix: qtwmaggg
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: ''
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  28e0666d-9435-4ecc-a982-159f66e10a7a: # Label
    columnSuffix: kpnuujue
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  a690e150-8755-4a1a-b7ff-02574430df1f: # Options
    columnSuffix: egaoerdi
    contentColumnType: text
    fieldGroup: null
    handle: options
    instructions: ''
    name: Options
    searchable: true
    settings:
      addRowLabel: 'Add an option'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Option Label'
                -
                  - handle
                  - optionLabel
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Value
                -
                  - handle
                  - value
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: ''
      minRows: '1'
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Table
  fc8eb0ae-eff2-4677-b3f0-c5af3d8d2a35: # Required
    columnSuffix: cmffdpna
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
handle: checkboxes
name: CheckBoxes
sortOrder: 6
