field: a9aeaad5-0a9e-4e5f-90c6-be37560cc464 # Content Modules
fieldLayouts:
  14c9275a-9d3e-4060-83a4-f559e3a644d0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 154618b9-8cee-4472-9df5-c41fb2548a3b # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38f4d475-345a-4dc6-8a7b-1ea220d31de7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 58226406-eba8-48e4-b665-a507ed627ac3 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 260dd7ce-b0bb-4ab7-aef3-78e98e29df48
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: aa333c04-32dc-4d7e-966a-729d825ad640 # Image 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fddd9e22-1bbf-420c-ab2b-c66def2ad50b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: faf84839-506f-4b4c-8a0d-0b2aaf333c88 # Block 1 Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5706510c-e979-4dfc-bf16-f04d42516976
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c23fe86-2db3-4d5c-9342-377a091be1ad # Block 1 Sub Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68c33f58-3353-4e94-b345-09e4eafa8267
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1b273cdc-d0a3-45b7-92cf-b15a5aa7a53b # Block 1 Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2eabd286-708d-499c-b7b5-e5b2247ea447
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 144726a0-ccad-4a4a-86e1-f0c40ec5ad1a # Block 2 Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6efa0b17-48ce-4261-a1df-4e3798a19678
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: edd3e836-88f6-4046-b55d-3385ee411c83 # Block 2 Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 844b5d94-8199-4b2f-8abe-247e1f2756dd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4442c1d6-016d-439c-9cbb-c07f02431e2f # Block 2 Sub Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf2f1808-eceb-4d19-9336-4be563c6732d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f991768d-cef9-44ff-a740-21129a517739 # Block 2 Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a5399b3-17d1-4e80-8436-b1dfbc6b68ad
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f9e85a5e-818b-4fc2-b679-dc7e5ecd4b1e
        userCondition: null
fields:
  1b273cdc-d0a3-45b7-92cf-b15a5aa7a53b: # Block 1 Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: block1Body
    instructions: null
    name: 'Block 1 Body'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 45ee12db-a387-4bf5-bf41-95d8744b1ffa # Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      showWordCount: false
      sourceEditingGroups: '*'
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  8c23fe86-2db3-4d5c-9342-377a091be1ad: # Block 1 Sub Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: block1SubHeadline
    instructions: null
    name: 'Block 1 Sub Headline'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4442c1d6-016d-439c-9cbb-c07f02431e2f: # Block 2 Sub Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: block2SubHeadline
    instructions: null
    name: 'Block 2 Sub Headline'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  144726a0-ccad-4a4a-86e1-f0c40ec5ad1a: # Block 2 Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: block2Image
    instructions: null
    name: 'Block 2 Image'
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  154618b9-8cee-4472-9df5-c41fb2548a3b: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  58226406-eba8-48e4-b665-a507ed627ac3: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: null
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 45ee12db-a387-4bf5-bf41-95d8744b1ffa # Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      showWordCount: false
      sourceEditingGroups: '*'
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  aa333c04-32dc-4d7e-966a-729d825ad640: # Image 1
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image1
    instructions: null
    name: 'Image 1'
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  edd3e836-88f6-4046-b55d-3385ee411c83: # Block 2 Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: block2Headline
    instructions: null
    name: 'Block 2 Headline'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f991768d-cef9-44ff-a740-21129a517739: # Block 2 Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: block2Body
    instructions: null
    name: 'Block 2 Body'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 45ee12db-a387-4bf5-bf41-95d8744b1ffa # Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      showWordCount: false
      sourceEditingGroups: '*'
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  faf84839-506f-4b4c-8a0d-0b2aaf333c88: # Block 1 Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: block1Headline
    instructions: null
    name: 'Block 1 Headline'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: contentBlockStaggered
name: 'Content Block Staggered'
sortOrder: 6
