field: a9aeaad5-0a9e-4e5f-90c6-be37560cc464 # Content Modules
fieldLayouts:
  80d987f1-a8b9-484b-86e5-21a00db4ae91:
    tabs:
      -
        elements:
          -
            fieldUid: 7531473a-5454-4ad2-8800-c55e9ac6675c # Block 1 Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 03728d78-c381-4018-ac8e-5aff2d8b873f # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0008d7da-9e97-4c33-b760-17a1d8e0c024 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 755f3e9f-d4d9-4376-af51-fcd63c5344e5 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cce2e1ed-7e08-49be-9c32-cc4edadbd8f1 # Block 1 BG Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 90b0550c-f986-4d82-88cb-9fcc2560ceaf # Block 2 Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f7a8289f-e018-449a-9605-77399b92d5b9 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 73a35c6c-2f2d-4147-8502-e427c0979fb2 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eaab0929-d90b-4e5a-a181-b4c6c0c774fa # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 116b6bce-8ec6-4074-9747-927e46bf5f36 # Block 2 BG Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0008d7da-9e97-4c33-b760-17a1d8e0c024: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: ''
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  73a35c6c-2f2d-4147-8502-e427c0979fb2: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: block2Body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: ''
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  90b0550c-f986-4d82-88cb-9fcc2560ceaf: # Block 2 Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: block2Image
    instructions: ''
    name: 'Block 2 Image'
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  116b6bce-8ec6-4074-9747-927e46bf5f36: # Block 2 BG Color
    columnSuffix: null
    contentColumnType: string(7)
    fieldGroup: null
    handle: block2BgColor
    instructions: ''
    name: 'Block 2 BG Color'
    searchable: true
    settings:
      defaultColor: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  755f3e9f-d4d9-4376-af51-fcd63c5344e5: # Button
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: button
    instructions: ''
    name: Button
    searchable: true
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      defaultText: ''
      selectLinkText: ''
      types:
        __assoc__:
          -
            - fruitstudios\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
                -
                  - allowAlias
                  - '1'
                -
                  - allowMailto
                  - '1'
                -
                  - allowHash
                  - '1'
                -
                  - allowPaths
                  - '1'
          -
            - fruitstudios\linkit\models\Twitter
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Facebook
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Instagram
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\LinkedIn
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Entry
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select an entry'
          -
            - fruitstudios\linkit\models\Category
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select a category'
          -
            - fruitstudios\linkit\models\Asset
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select an asset'
          -
            - fruitstudios\linkit\models\User
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
                -
                  - userPath
                  - ''
          -
            - fruitstudios\linkit\models\Product
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select an entry'
    translationKeyFormat: null
    translationMethod: none
    type: fruitstudios\linkit\fields\LinkitField
  03728d78-c381-4018-ac8e-5aff2d8b873f: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '2'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7531473a-5454-4ad2-8800-c55e9ac6675c: # Block 1 Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: block1Image
    instructions: ''
    name: 'Block 1 Image'
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  cce2e1ed-7e08-49be-9c32-cc4edadbd8f1: # Block 1 BG Color
    columnSuffix: null
    contentColumnType: string(7)
    fieldGroup: null
    handle: block1BgColor
    instructions: ''
    name: 'Block 1 BG Color'
    searchable: true
    settings:
      defaultColor: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  eaab0929-d90b-4e5a-a181-b4c6c0c774fa: # Button
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: block2Button
    instructions: ''
    name: Button
    searchable: true
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      defaultText: ''
      selectLinkText: ''
      types:
        __assoc__:
          -
            - fruitstudios\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
                -
                  - allowAlias
                  - '1'
                -
                  - allowMailto
                  - '1'
                -
                  - allowHash
                  - '1'
                -
                  - allowPaths
                  - '1'
          -
            - fruitstudios\linkit\models\Twitter
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Facebook
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Instagram
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\LinkedIn
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Entry
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select an entry'
          -
            - fruitstudios\linkit\models\Category
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select a category'
          -
            - fruitstudios\linkit\models\Asset
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select an asset'
          -
            - fruitstudios\linkit\models\User
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
                -
                  - userPath
                  - ''
          -
            - fruitstudios\linkit\models\Product
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select an entry'
    translationKeyFormat: null
    translationMethod: none
    type: fruitstudios\linkit\fields\LinkitField
  f7a8289f-e018-449a-9605-77399b92d5b9: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: block2Headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '2'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: doubleCta
name: 'Double CTA'
sortOrder: 4
