field: ed70687a-ec3a-482b-aa3a-e6643ae25324 # Accordion Drawer
fieldLayouts:
  2bc21a65-1333-4633-ad30-571259ff84f2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6d176f65-7a88-4847-8591-1f85fd2bd695 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6f1b5fa-a071-4541-8305-02e2cddfa2f8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 11f35649-7e8c-4815-b33e-e1d0703ec708 # Drawer Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85275af7-4fb7-42d8-b69e-c3085bc5cef1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9daa2b1f-2b23-4088-ad8e-e40c21428791
        userCondition: null
fields:
  6d176f65-7a88-4847-8591-1f85fd2bd695: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  11f35649-7e8c-4815-b33e-e1d0703ec708: # Drawer Content
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: drawerContent
    instructions: null
    name: 'Drawer Content'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: drawer
name: Drawer
sortOrder: 1
