field: 6a35777e-50b5-46b1-b3e6-294e9553bd87 # Basic Form Fields
fieldLayouts:
  df808df8-2e6c-465b-ad06-a97a398af092:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 45d7a531-d9d3-4444-8ba1-3ec91cf8b6ac # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b7adddc7-8dd9-4bd6-ab8f-ab68131b46a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dd7f88ee-c166-4f12-b4fa-b0e59f0ac85a # Handle
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7389e962-3e16-46d5-82eb-05b8a518e3fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 802e6b2e-1fa3-49bd-a1f5-7242fa2b10ec # Options
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ff33f18-330f-45ff-9a45-0450f776b9a3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0f10e286-6da3-4f9e-b4ab-2c29faf6bc77 # Required
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86619358-1c37-4b2c-b991-70f5268f5a82
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4a4e6013-adf9-4738-af0f-762f181e21e1
        userCondition: null
fields:
  0f10e286-6da3-4f9e-b4ab-2c29faf6bc77: # Required
    columnSuffix: ikskfzgd
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  45d7a531-d9d3-4444-8ba1-3ec91cf8b6ac: # Label
    columnSuffix: sjyyrddb
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  802e6b2e-1fa3-49bd-a1f5-7242fa2b10ec: # Options
    columnSuffix: hoojqxic
    contentColumnType: text
    fieldGroup: null
    handle: options
    instructions: null
    name: Options
    searchable: true
    settings:
      addRowLabel: 'Add an option'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Option Label'
                -
                  - handle
                  - optionLabel
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Value
                -
                  - handle
                  - value
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: null
      minRows: 1
      staticRows: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Table
  dd7f88ee-c166-4f12-b4fa-b0e59f0ac85a: # Handle
    columnSuffix: dedxzbud
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: null
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: dropdown
name: Dropdown
sortOrder: 3
