field: cf76daff-2c39-465f-8d83-9acd3b0d172b # Materials
fieldLayouts:
  e8dba11a-8091-4151-8148-d7d7340441e4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 859c20f1-11f4-4840-9084-54bc39858e14 # File
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70f06cc2-3e25-4ede-8ce2-0994858072c3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5098ce89-d551-48cf-9e56-546b4c67b03c # Icon Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a39a42f-cda9-45f9-a369-a5060d274990
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0ff22985-cdfe-4669-bb7f-dd57b0571bbe
        userCondition: null
fields:
  859c20f1-11f4-4840-9084-54bc39858e14: # File
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: file
    instructions: null
    name: File
    searchable: true
    settings:
      allowCustomText: true
      allowTarget: false
      defaultText: null
      selectLinkText: ''
      types:
        __assoc__:
          -
            - presseddigital\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
                -
                  - allowAlias
                  - '1'
                -
                  - allowMailto
                  - '1'
                -
                  - allowHash
                  - '1'
                -
                  - allowPaths
                  - '1'
          -
            - presseddigital\linkit\models\Twitter
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Facebook
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Instagram
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\LinkedIn
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Entry
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select asset'
          -
            - presseddigital\linkit\models\Category
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select a category'
          -
            - presseddigital\linkit\models\Asset
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select an asset'
          -
            - presseddigital\linkit\models\User
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
                -
                  - userPath
                  - ''
          -
            - presseddigital\linkit\models\Product
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select asset'
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\linkit\fields\LinkitField
  5098ce89-d551-48cf-9e56-546b4c67b03c: # Icon Type
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: iconType
    instructions: null
    name: 'Icon Type'
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - none
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - File
            -
              - value
              - file
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Video
            -
              - value
              - video
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: file
name: File
sortOrder: 1
