field: 6a35777e-50b5-46b1-b3e6-294e9553bd87 # Basic Form Fields
fieldLayouts:
  030725cd-b195-483b-80c7-6b841de35221:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ae9d1eda-6207-4b13-bb10-b6e78dc707e7 # Handle
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0bbaa7a8-382d-4332-a1c9-c42a3d8f241a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5b6c451-dc88-4044-a610-cc328915b6ee # Hidden Value
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b6a99e1-c2d0-4d39-aaa4-97fbb0570c99
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: faadd356-7b61-4b85-a17a-72fba437c852
        userCondition: null
fields:
  ae9d1eda-6207-4b13-bb10-b6e78dc707e7: # Handle
    columnSuffix: ngckpfks
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: 'This field will not visible in the form, just in the source code'
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  e5b6c451-dc88-4044-a610-cc328915b6ee: # Hidden Value
    columnSuffix: hjgitcqx
    contentColumnType: text
    fieldGroup: null
    handle: hiddenValue
    instructions: 'You can use twig code'
    name: 'Hidden Value'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: '{{ craft.request.path }}'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: hidden
name: Hidden
sortOrder: 7
