field: e36ca748-a185-4fc2-b8c0-b0d4213bf0c8 # Comparison Attributes
fieldLayouts:
  d564b70d-fe8b-4746-b4a5-aed8147726e6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c6a86332-cec0-423e-a200-4b3de8509a95 # Key Ingredients
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5548f98e-e7a6-482a-8bbd-a1bde1798cdc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eabb0b9e-d3d4-4e7b-a6f1-a48b8f9a05dd
        userCondition: null
fields:
  c6a86332-cec0-423e-a200-4b3de8509a95: # Key Ingredients
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: keyIngredients
    instructions: null
    name: 'Key Ingredients'
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: null
      columns:
        __assoc__:
          -
            - 32faaac3-a839-4748-aa11-945c9ee98336 # Ingredients
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 8a9a811a-3a61-4edf-b448-213fd07541d0 # Precursor Potential
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_16_keyingredients}}'
      fieldLayout: table
      maxRows: 2
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add Ingredient'
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: hormones
name: Hormones
sortOrder: 3
