field: e36ca748-a185-4fc2-b8c0-b0d4213bf0c8 # Comparison Attributes
fieldLayouts:
  da2222d8-6abf-407b-ab26-cefee65be4ee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c0016ea1-20c0-4590-8cc7-1359f3dadac0 # Key Ingredients
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76c24d98-10e2-41f7-b786-3ce0d525aa02
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6f36489a-c08f-4a78-b3ef-c7a16015bed7
        userCondition: null
fields:
  c0016ea1-20c0-4590-8cc7-1359f3dadac0: # Key Ingredients
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: keyIngredients
    instructions: null
    name: 'Key Ingredients'
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: null
      columns:
        __assoc__:
          -
            - aba94e3f-0f87-4c20-a5fb-27aa0dc5ab3a # Ingredients
            -
              __assoc__:
                -
                  - width
                  - 70%
          -
            - 69300f6d-e971-4ea3-ae30-550b3f2449f7 # Precursor Potential
            -
              __assoc__:
                -
                  - width
                  - 30%
      contentTable: '{{%stc_14_keyingredients}}'
      fieldLayout: table
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add Ingredient'
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: impactfulIngredients
name: 'Impactful ingredients'
sortOrder: 1
