field: a9aeaad5-0a9e-4e5f-90c6-be37560cc464 # Content Modules
fieldLayouts:
  1302e41b-e3f2-4312-95d9-b8d96c9ee879:
    tabs:
      -
        elements:
          -
            fieldUid: 1a7dbb25-bb4f-4039-9a1a-49a727ed8a9b # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0c30c94f-3304-4354-8d31-58ceeb9f0f9a # Sub Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ea628848-2ee7-4dee-8d16-12284700d5d6 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1f85f594-bab5-499f-85b9-c9f89ca211e9 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 65256469-cb0a-466f-b0f6-1622df1cf8d8 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7e4d0918-e3e2-44b8-996f-f35030e5dcc5 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0c30c94f-3304-4354-8d31-58ceeb9f0f9a: # Sub Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: subHeadline
    instructions: ''
    name: 'Sub Headline'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  1a7dbb25-bb4f-4039-9a1a-49a727ed8a9b: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  1f85f594-bab5-499f-85b9-c9f89ca211e9: # Button
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: button
    instructions: ''
    name: Button
    searchable: true
    settings:
      allowCustomText: ''
      allowTarget: ''
      defaultText: ''
      selectLinkText: ''
      types:
        __assoc__:
          -
            - presseddigital\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
                -
                  - allowAlias
                  - '1'
                -
                  - allowMailto
                  - '1'
                -
                  - allowHash
                  - '1'
                -
                  - allowPaths
                  - '1'
          -
            - presseddigital\linkit\models\Twitter
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Facebook
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Instagram
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\LinkedIn
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Entry
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select an entry'
          -
            - presseddigital\linkit\models\Category
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select a category'
          -
            - presseddigital\linkit\models\Asset
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select an asset'
          -
            - presseddigital\linkit\models\User
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
                -
                  - userPath
                  - ''
          -
            - presseddigital\linkit\models\Product
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select an entry'
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\linkit\fields\LinkitField
  7e4d0918-e3e2-44b8-996f-f35030e5dcc5: # Layout
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: ''
    name: Layout
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  65256469-cb0a-466f-b0f6-1622df1cf8d8: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ea628848-2ee7-4dee-8d16-12284700d5d6: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: ''
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: mediaObject
name: 'Media Object'
sortOrder: 7
