field: e36ca748-a185-4fc2-b8c0-b0d4213bf0c8 # Comparison Attributes
fieldLayouts:
  812e70ea-7cb9-43f6-a85f-9a2cdbf910cc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0e5103db-1b8c-4e6b-bdb0-ed490e0ede55 # Additional Information
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82301c9c-3dfc-4186-9c4a-4d357c3f4f92
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f988c805-8596-45a3-913b-86607cf44ae9
        userCondition: null
fields:
  0e5103db-1b8c-4e6b-bdb0-ed490e0ede55: # Additional Information
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: additionalInformation
    instructions: null
    name: 'Additional Information'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 42413eea-7d73-4c19-ba3d-37a4d3879182 # Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      sourceEditingGroups:
        - __ADMINS__
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: other
name: Other
sortOrder: 5
