field: e36ca748-a185-4fc2-b8c0-b0d4213bf0c8 # Comparison Attributes
fieldLayouts:
  812e70ea-7cb9-43f6-a85f-9a2cdbf910cc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0e5103db-1b8c-4e6b-bdb0-ed490e0ede55 # Additional Information
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea3323aa-ecf6-44d4-868d-300f05cde564
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4dacb7e7-308d-42c7-8209-de8ed2d9500f
        userCondition: null
fields:
  0e5103db-1b8c-4e6b-bdb0-ed490e0ede55: # Additional Information
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: additionalInformation
    instructions: null
    name: 'Additional Information'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      ckeConfig: 3c7d8a91-2b4e-4f63-9c1d-8e5f6a7b9c0d # Standard
      columnType: text
      defaultTransform: ''
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: other
name: Other
sortOrder: 5
