field: 6a35777e-50b5-46b1-b3e6-294e9553bd87 # Basic Form Fields
fieldLayouts:
  eab418a2-a39b-4653-bc07-44c735f7e856:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ec73f3f2-7c8a-48eb-a096-c95f8c6f90ff # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 333ad13b-1a16-48b3-92a9-02a9b6261da2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 29be2be4-fba9-43c0-8186-7f7b51087d55 # Handle
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a7d356a-5d30-4cbd-b3e9-f032db9a65f0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 74f9c2ae-2b69-4fc3-8897-3544cdcf6130 # Placeholder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34c80569-7e01-433a-a6ea-2e8bf4282792
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8ce28b8f-8420-4ff3-9592-7038280ede1b # Initial Rows
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f547c361-c1a8-4b27-b4c7-ad27fa705afe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e3c2c8c1-4418-49b4-bf0f-ebe7e4b78874 # Required
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24791bba-a1e6-4d34-88f3-0e54753dc439
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 149dd90e-85f5-4a49-9b3f-908e04aa22de
        userCondition: null
fields:
  8ce28b8f-8420-4ff3-9592-7038280ede1b: # Initial Rows
    columnSuffix: nkxjhasq
    contentColumnType: integer(10)
    fieldGroup: null
    handle: initialRows
    instructions: null
    name: 'Initial Rows'
    searchable: true
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 2
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Number
  29be2be4-fba9-43c0-8186-7f7b51087d55: # Handle
    columnSuffix: jgbqqflc
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: null
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  74f9c2ae-2b69-4fc3-8897-3544cdcf6130: # Placeholder
    columnSuffix: iumfsajx
    contentColumnType: text
    fieldGroup: null
    handle: placeholder
    instructions: null
    name: Placeholder
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  e3c2c8c1-4418-49b4-bf0f-ebe7e4b78874: # Required
    columnSuffix: syuraism
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  ec73f3f2-7c8a-48eb-a096-c95f8c6f90ff: # Label
    columnSuffix: mdhuevnh
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: paragraph
name: Paragraph
sortOrder: 2
