field: 6a35777e-50b5-46b1-b3e6-294e9553bd87 # Basic Form Fields
fieldLayouts:
  919c5a0e-54f5-48d8-b42f-65a62fd532ee:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1a8bf3a6-8f00-4c33-b0a3-7b63a1e72456 # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60432318-0626-40e5-ba57-30d5feadb9dd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9809e321-bc6a-45ed-9b98-d597844a5fa8 # Handle
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59a54bad-a7bb-422c-b04d-bd74ecdc5606
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7105a79e-5c08-451d-acd8-46713e74323f # Options
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 299895e4-a4d8-4510-a6d4-d96fd11b6691
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 13a9cb06-b512-4e58-8b1a-7c2cfb183eff # Required
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05477ed7-4a3c-461e-8a7c-9f934d94c72e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d1d014cd-6177-4c40-92b7-d7b1847c3e9b
        userCondition: null
fields:
  1a8bf3a6-8f00-4c33-b0a3-7b63a1e72456: # Label
    columnSuffix: dvgazafl
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  13a9cb06-b512-4e58-8b1a-7c2cfb183eff: # Required
    columnSuffix: xpaxcsgu
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  7105a79e-5c08-451d-acd8-46713e74323f: # Options
    columnSuffix: bkjehuit
    contentColumnType: text
    fieldGroup: null
    handle: options
    instructions: null
    name: Options
    searchable: true
    settings:
      addRowLabel: 'Add an option'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Option Label'
                -
                  - handle
                  - optionLabel
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Value
                -
                  - handle
                  - value
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: null
      minRows: 1
      staticRows: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Table
  9809e321-bc6a-45ed-9b98-d597844a5fa8: # Handle
    columnSuffix: cydahyfz
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: null
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: radioButtons
name: 'Radio Buttons'
sortOrder: 4
