field: 6a35777e-50b5-46b1-b3e6-294e9553bd87 # Basic Form Fields
fieldLayouts:
  1729826e-7300-4657-980f-ebd98c038af3:
    tabs:
      -
        elements:
          -
            fieldUid: 1254ba87-3766-4034-a45f-47babecaf618 # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0ae84908-a5d0-4016-a0d1-9db23664723f # Handle
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5b13d1bf-e083-45cb-9eb8-f36892437118 # Placeholder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 30d585b0-ed19-42a7-ba41-552405a2dfac # Required
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0ae84908-a5d0-4016-a0d1-9db23664723f: # Handle
    columnSuffix: irkdlubz
    contentColumnType: text
    fieldGroup: null
    handle: fieldHandle
    instructions: ''
    name: Handle
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  5b13d1bf-e083-45cb-9eb8-f36892437118: # Placeholder
    columnSuffix: arwqapzz
    contentColumnType: text
    fieldGroup: null
    handle: placeholder
    instructions: ''
    name: Placeholder
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  30d585b0-ed19-42a7-ba41-552405a2dfac: # Required
    columnSuffix: obqygjoc
    contentColumnType: boolean
    fieldGroup: null
    handle: required
    instructions: 'This field is required?'
    name: Required
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  1254ba87-3766-4034-a45f-47babecaf618: # Label
    columnSuffix: iwafvqvi
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: Label
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: singleLine
name: 'Single Line'
sortOrder: 1
