field: a9aeaad5-0a9e-4e5f-90c6-be37560cc464 # Content Modules
fieldLayouts:
  893c36cc-6a61-4b0b-a8e7-aa4e51537517:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3c8dc169-38f4-420f-a2be-e9cc76184735 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf8fe287-d00c-44d2-9f34-aa842bfc6b4e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9d5ab0eb-c6af-4ab4-8305-ed62dcd6972b # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dceacb2e-4234-4ad8-b1dd-2bdf69e08a9d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 159d1e6c-6d4d-4850-8522-b0ac3cf8cf0c
        userCondition: null
fields:
  3c8dc169-38f4-420f-a2be-e9cc76184735: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9d5ab0eb-c6af-4ab4-8305-ed62dcd6972b: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: null
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: false
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: textBlock
name: 'Text Block'
sortOrder: 8
