fieldLayouts:
  410c8804-dcff-4ef5-ab8c-e7f6e38d268c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: a9aeaad5-0a9e-4e5f-90c6-be37560cc464 # Content Modules
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 15437087-f989-4528-b5cd-e42a5aad58ad # SEO
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: healthcareProfessionalsOverview
hasTitleField: false
name: 'Healthcare Providers Overview'
section: 51f315e9-0e39-4e97-a846-073605f7e9bf # Healthcare Providers Overview
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
