fieldLayouts:
  99520263-2ebc-4d23-8770-8c68ecc11529:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d7b07c28-fe4f-469f-9ca1-7ff118eebfe2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a9aeaad5-0a9e-4e5f-90c6-be37560cc464 # Content Modules
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 221d5e2a-26af-4a94-ad7d-77615acea545
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 41a04c10-b29b-43b5-ae56-743206d3e535
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 15437087-f989-4528-b5cd-e42a5aad58ad # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38adbdab-0516-41d9-81b5-4003ff77b10e
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: e3b66096-5d0b-4c3b-ab5f-daeeb49da05e
        userCondition: null
handle: healthcareProfessionals
hasTitleField: true
name: 'Healthcare Professionals'
section: a7d38fe9-86e0-495c-9bca-a8567b4a1159 # Healthcare Providers
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
