fieldLayouts:
  31c6b935-037b-4de4-96e9-ec1ed86ee755:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6b820517-5ae7-436d-8e4b-0de56549b313
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a9aeaad5-0a9e-4e5f-90c6-be37560cc464 # Content Modules
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36139502-0002-4de9-ace0-d594c0bb4d25
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6df18d3f-5836-40a6-8573-89e867ab8dd0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 15437087-f989-4528-b5cd-e42a5aad58ad # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25496831-4e8d-42ce-aad6-4ebfa097f913
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 351d0152-a240-419e-9849-b31744761034
        userCondition: null
handle: homepage
hasTitleField: true
name: Homepage
section: e2114991-fe88-4d06-b236-dda841abc628 # Homepage
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
