fieldLayouts:
  1e45f2ee-0f37-4180-a88f-591730975a65:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 155b9888-8c70-46db-b933-1e91d520e35d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: efba5d6b-817b-4355-a4e4-bf25ea0efaea
        userCondition: null
handle: login
hasTitleField: false
name: Login
section: b5b15287-8bfd-4df9-b271-06ed382fb53d # Login
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
