fieldLayouts:
  a802922c-da11-4760-b726-94378d38a0bf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 20613287-c292-45ee-b321-2f720aec068a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e91746b9-71f0-4bd2-85e8-5e472ca29df7 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9538f20-441f-4c27-b29a-5269a266a8c6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 49e5c2c1-438f-4d0b-81cf-bee8735532de # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d004e5aa-1efc-4fb6-83f4-78bf2cfa730a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4f5a97f7-34f5-4b71-8ccc-e7a53f72315d # Body
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 833fc06a-807a-44f0-a5b3-475743ba26bd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bb37393d-7459-4b7c-932a-bd3f1aa80196 # Tags
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b1938c4-e45c-49c2-84d3-7492c8c6be14
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7b93d3ba-35ff-4d96-8f75-68768c6708b8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 15437087-f989-4528-b5cd-e42a5aad58ad # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 922630e1-be54-4226-be50-17dd6927eb8e
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 30c93298-69ce-4cff-a231-dd8a9e8fa651
        userCondition: null
handle: news
hasTitleField: true
name: News
section: 6c1630f3-e220-4731-8275-a2f31e2bda2d # News
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
