fieldLayouts:
  88c83f68-40e5-4995-b070-506dfe0adec0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8165c964-ab00-4b1d-bb85-32d4e9d08fb7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d0cdeae7-30fa-46b0-919b-c29303b44e97
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 15437087-f989-4528-b5cd-e42a5aad58ad # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2d4c815-5cb6-44cf-9f37-fe88bdcde34c
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 40628080-c55c-4303-9755-3d2df4a7056c
        userCondition: null
handle: productsLanding
hasTitleField: false
name: 'Products Landing'
section: cb37c8c8-928f-4175-946a-5cbecc60c2f2 # Products Landing
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
