fieldLayouts:
  efc6aac3-7cd3-4ff4-aa66-6134eed0e297:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 97915d6b-a5b1-49d8-9d90-4552c7394f80
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e568aed3-4264-4f2d-91a7-0e84797553c4
        userCondition: null
handle: resetPassword
hasTitleField: false
name: 'Reset Password'
section: cc788334-996f-492a-948f-c70687deaeb2 # Reset Password
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
