fieldLayouts:
  b93d21bc-cc40-42e2-abcc-ea5523e0cf4a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 60e95052-f5b6-41e1-acc6-82980ea8db5a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a0ddea2c-ec45-4213-b8dd-254fd0bc2954
        userCondition: null
handle: resetPassword
hasTitleField: false
name: 'Reset Password'
section: cc788334-996f-492a-948f-c70687deaeb2 # Reset Password
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
