fieldLayouts:
  4f98f062-6838-4eb1-bb1b-2382f12bef41:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b7cb389b-e868-41f0-bd85-881b375f9f17
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a1e696d0-3897-4193-b36f-7fd81d743334
        userCondition: null
handle: setPassword
hasTitleField: false
name: 'Set Password'
section: cb76e8e3-6bb1-48af-8d7b-7036fb02c03d # Set Password
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
