css: ".align-left { text-align: left; }\n.align-right { text-align: right; }\n.align-center { text-align: center; }\n.align-justify { text-align: justify; }\n"
headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Standard
options:
  alignment:
    options:
      -
        className: align-left
        name: left
      -
        className: align-right
        name: right
      -
        className: align-center
        name: center
      -
        className: align-justify
        name: justify
  heading:
    options:
      -
        class: ck-heading_heading1
        model: heading1
        title: 'Heading 1'
        view:
          classes:
            - h1
          name: h2
  htmlSupport:
    allow:
      -
        attributes: true
        classes: true
        styles: true
  style:
    definitions:
      -
        classes:
          - p-sm
        element: span
        name: Small
toolbar:
  - heading
  - style
  - '|'
  - bold
  - italic
  - '|'
  - link
  - '|'
  - bulletedList
  - numberedList
  - blockQuote
  - '|'
  - alignment
  - horizontalLine
  - insertImage
  - '|'
  - sourceEditing
