defaultPlacement: end
fieldLayouts:
  bdf47f17-c308-4d90-9b6c-43f3802dbc06:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 03118dec-d70c-4680-964e-36bdf66b9155
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e6321d75-72f3-4f23-9563-e9335aaaafb7
        userCondition: null
handle: ingredients
name: Ingredients
siteSettings:
  9980c1bd-fa51-4b79-b81f-bf4576d54b1e: # NeuroScience
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: cc22899d-b274-4bd6-a6ea-ec8f71a36e50
