defaultPlacement: end
fieldLayouts:
  28acc836-7370-459a-bd47-dfe7e02f8f1c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 66a2a0b8-4a25-41ae-9d7e-53a3b6816483
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4f5a97f7-34f5-4b71-8ccc-e7a53f72315d # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58c84e78-0323-4193-909b-512b4ae74176
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f19e786d-b323-47bb-b6ca-51459f2d2e69
        userCondition: null
handle: lotNumbers
name: 'Lot Numbers'
siteSettings:
  9980c1bd-fa51-4b79-b81f-bf4576d54b1e: # NeuroScience
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 9fe72288-c3a4-4dd7-a3d3-c9e2efab5015
