defaultPlacement: end
fieldLayouts:
  07c2f9e2-e636-406f-957c-3dfd769fa49e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 3a7bcb0b-6351-4f66-bf4c-275d18c076b9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ff235267-c1f4-420c-b572-02e790f20c78
        userCondition: null
handle: pathways
name: 'QR Scan Pathways'
siteSettings:
  9980c1bd-fa51-4b79-b81f-bf4576d54b1e: # NeuroScience
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 029a7920-e8cc-41e1-a8f2-629c84663662
