defaultPlacement: end
fieldLayouts:
  5418b9b5-fa9a-456d-913a-a516a97241db:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 5a03b034-f5f7-4dbc-a627-714ba4df2833
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 47fed24d-3042-4cef-a451-2572d0be8b41
        userCondition: null
handle: promotions3
name: Promotions
siteSettings:
  9980c1bd-fa51-4b79-b81f-bf4576d54b1e: # NeuroScience
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 015beb84-cbfe-4748-b53e-d43bfee1cdfd
