defaultPlacement: end
fieldLayouts:
  254c8632-805e-4da0-90d0-093f8866a7d6:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: promotions3
name: Promotions
siteSettings:
  9980c1bd-fa51-4b79-b81f-bf4576d54b1e: # NeuroScience
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 015beb84-cbfe-4748-b53e-d43bfee1cdfd
