defaultPlacement: end
fieldLayouts:
  8f6cd17e-923c-4d9c-b579-ad6bd5216890:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 489607f9-79f4-49d7-8379-d1167452410b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c08787ff-fe9b-47a9-ab09-7907cb742b23
        userCondition: null
handle: promotions3
name: Promotions
siteSettings:
  9980c1bd-fa51-4b79-b81f-bf4576d54b1e: # NeuroScience
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 015beb84-cbfe-4748-b53e-d43bfee1cdfd
