defaultPlacement: end
fieldLayouts:
  626c10f1-8407-4605-bd7a-5e7a499136cd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 3db16dd1-8524-447c-867f-1f13a3250cdc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4f5a97f7-34f5-4b71-8ccc-e7a53f72315d # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7fc3ac34-8dcb-4861-948a-8e8d353dcab1
            userCondition: null
            warning: null
            width: 100
        name: Citation
        uid: 3b812623-ce6c-4115-b234-35a64fd45ff7
        userCondition: null
handle: resources
name: Resources
siteSettings:
  9980c1bd-fa51-4b79-b81f-bf4576d54b1e: # NeuroScience
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 111afd58-caf2-4599-ae37-253d2e3d3ea9
