defaultPlacement: end
fieldLayouts:
  626c10f1-8407-4605-bd7a-5e7a499136cd:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 4f5a97f7-34f5-4b71-8ccc-e7a53f72315d # Body
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Citation
        sortOrder: 1
handle: resources
name: Resources
siteSettings:
  9980c1bd-fa51-4b79-b81f-bf4576d54b1e: # NeuroScience
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 111afd58-caf2-4599-ae37-253d2e3d3ea9
