defaultPlacement: end
fieldLayouts:
  df68cb0d-af3b-4eaa-8269-fc0b6ee5c9bf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: e9d4b5ab-2ae3-4ed3-ad82-82acb52febf2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e813bfde-0e1d-41f1-8bdf-2a9c7483d3c1
        userCondition: null
handle: sleepSymptoms
name: 'Sleep Symptoms'
siteSettings:
  9980c1bd-fa51-4b79-b81f-bf4576d54b1e: # NeuroScience
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: add00a09-3297-4ddd-874b-5ad176614535
