defaultPlacement: end
fieldLayouts:
  06b50a35-631b-4753-a2e1-99cf4c917886:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: updatedPathways
name: 'Updated Pathways'
siteSettings:
  9980c1bd-fa51-4b79-b81f-bf4576d54b1e: # NeuroScience
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: f8746aa0-4e37-45c1-9910-8f881493dfd3
