fieldLayouts:
  23243328-7087-42de-994a-e82ad085690c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fs: documents
handle: documents
hasUrls: true
name: Documents
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
url: '@baseUrl/images/documents'
