fieldLayouts:
  02ff320e-7b7a-40ed-bbe9-ce6b9bf8652f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9ae0de43-eddb-40f7-aab3-580224031d69
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 64415da0-9489-49a2-ad87-5e04debc4aeb
        userCondition: null
fs: pirPdfs
handle: pirPdfs
name: 'PIR PDFs'
sortOrder: 6
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
