fieldLayouts:
  f6d0c568-53eb-4df6-b124-767f07cc8f99:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 394e7ba8-0943-4537-9d8b-a221c109ca62
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0ef230c4-df5b-4b3b-b268-f39075fc2463
        userCondition: null
fs: productImages
handle: productImages
name: 'Product Images'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
