fieldLayouts:
  f6d0c568-53eb-4df6-b124-767f07cc8f99:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4302d295-5c72-4821-98c9-f1d916493078
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ebd58a7a-a1e1-4c11-84f4-fbe95c61dba8
        userCondition: null
fs: productImages
handle: productImages
name: 'Product Images'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
