fieldLayouts:
  f6d0c568-53eb-4df6-b124-767f07cc8f99:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: productImages
hasUrls: true
name: 'Product Images'
settings:
  path: images/products
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: craft\volumes\Local
url: '@baseUrl/images/products'
