fieldLayouts:
  c6391e57-17cd-49a5-a7b1-7be757c0dff2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 7739ceb0-2f16-4ad6-bbdc-531231576b6f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b0ff71a5-b127-4edc-bffd-462073cd18b8
        userCondition: null
fs: salesReps
handle: salesReps
name: 'Sales Reps'
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
