fieldLayouts:
  3607f14e-974e-4ec3-a729-f7319f7b3299:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: surveys
hasUrls: true
name: Surveys
settings:
  path: surveys
sortOrder: 8
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: craft\volumes\Local
url: '@baseUrl/surveys'
