fieldLayouts:
  4c5a6b00-694e-4326-940a-d80f1a5b4bc9:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fs: userUploads
handle: userUploads
hasUrls: false
name: 'User Uploads'
sortOrder: 5
titleTranslationKeyFormat: null
titleTranslationMethod: site
url: null
