fieldLayouts:
  f4134a48-3cc7-4e72-914b-066a49338e50:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c22dcbd8-74d0-47e4-afdf-b3614317034b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d0d3ddbe-aaa0-425a-8e4a-f9915dd7688c
        userCondition: null
fs: userPhotos
handle: userPhotos
name: 'User Photos'
sortOrder: 7
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
