columnSuffix: null
contentColumnType: string
fieldGroup: 81b70b61-6757-484e-ace4-d9f92781c701 # Commerce
handle: additionalTiles
instructions: ''
name: 'Additional Tiles'
searchable: true
settings:
  columns:
    __assoc__:
      -
        - f09d786a-e956-46a1-bab2-e17e8bffec63 # Icon
        -
          __assoc__:
            -
              - width
              - ''
      -
        - bb1ecfc9-053e-4250-be95-e4e8315a3d58 # Headline
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 322252f2-9500-4211-a3e5-71abdb9f8811 # Content
        -
          __assoc__:
            -
              - width
              - ''
      -
        - a84f30b0-7cd0-4eb1-a2ca-dd9b5215f66b # Link
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_additionaltiles}}'
  fieldLayout: row
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add a tile'
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
