columnSuffix: kqjilssa
contentColumnType: string
fieldGroup: a8843661-a567-4e21-8928-2108d60edafe # Avatax
handle: addressPhone
instructions: null
name: 'Phone Number'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: string
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
