columnSuffix: null
contentColumnType: string
fieldGroup: c2f1cc8b-c74b-46fa-a18a-d11848cc3965 # Global Fields
handle: alertMessage
instructions: null
name: 'Alert Message'
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    156:
      __assoc__:
        -
          - width
          - '60'
    157:
      __assoc__:
        -
          - width
          - '30'
    158:
      __assoc__:
        -
          - width
          - 10%
  contentTable: '{{%stc_alertmessage}}'
  fieldLayout: table
  maxRows: 1
  minRows: 1
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add alert'
  staticField: null
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
