columnSuffix: null
contentColumnType: text
fieldGroup: 4a7f50ea-95ad-4b62-a380-10a458ee6d34 # Mobile Application
handle: appToken
instructions: null
name: 'App Token'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
