columnSuffix: null
contentColumnType: string
fieldGroup: 9fd48f5f-c27d-4d13-b181-47a720fb98c6 # Default
handle: contentModules
instructions: ''
name: 'Content Modules'
searchable: true
settings:
  contentTable: '{{%matrixcontent_contentmodules}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
