columnSuffix: null
contentColumnType: string
fieldGroup: 9a98c4e1-a799-42f0-a4ce-ba07bd38df16 # Forms
handle: contactPhone
instructions: null
name: Phone
searchable: true
settings:
  byteLimit: null
  charLimit: 15
  code: false
  columnType: string
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
