columnSuffix: null
contentColumnType: text
fieldGroup: 6329f165-1216-4dee-8071-071c8c5cb854 # Comparison table
handle: ct_references
instructions: null
name: References
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 3c7d8a91-2b4e-4f63-9c1d-8e5f6a7b9c0d # Standard
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
