columnSuffix: wpimkcgx
contentColumnType: boolean
fieldGroup: 9fd48f5f-c27d-4d13-b181-47a720fb98c6 # Default
handle: disableInPf
instructions: ''
name: 'Disable in PF?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
