columnSuffix: null
contentColumnType: text
fieldGroup: 81b70b61-6757-484e-ace4-d9f92781c701 # Commerce
handle: disclaimers
instructions: ''
name: Disclaimers
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: ''
  redactorConfig: Standard.json
  removeEmptyTags: true
  removeInlineStyles: true
  removeNbsp: true
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
