columnSuffix: null
contentColumnType: boolean
fieldGroup: aa06a404-5068-4c0d-9e2d-845531dba984 # Register Form
handle: eventRegistration
instructions: null
name: 'Event Registration'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
