columnSuffix: null
contentColumnType: string
fieldGroup: a8843661-a567-4e21-8928-2108d60edafe # Avatax
handle: hcpProductsStore
instructions: ''
name: 'Product Selection'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\commerce\fields\Products
