columnSuffix: null
contentColumnType: string
fieldGroup: a8843661-a567-4e21-8928-2108d60edafe # Avatax
handle: hcpProductsStore
instructions: null
name: 'Product Selection'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\commerce\fields\Products
