columnSuffix: ccwbrttg
contentColumnType: text
fieldGroup: 228fdc9a-5d24-44f0-89d9-fd7ddaf7524f # Patients
handle: hcpSharingDiscountDetail
instructions: ''
name: 'HCP Sharing Discount Detail'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
