columnSuffix: null
contentColumnType: boolean
fieldGroup: 81b70b61-6757-484e-ace4-d9f92781c701 # Commerce
handle: hideBottleCount
instructions: null
name: 'Hide bottle count?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
