columnSuffix: null
contentColumnType: string
fieldGroup: aa06a404-5068-4c0d-9e2d-845531dba984 # Register Form
handle: howDidYouHearAboutNeuroscience
instructions: null
name: 'How did you hear about NeuroScience?'
searchable: true
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - Colleague
        -
          - value
          - colleague
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Internet
        -
          - value
          - internet
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Sales Rep'
        -
          - value
          - salesRep
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Advertisement
        -
          - value
          - advertisement
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Patient
        -
          - value
          - patient
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Seminar
        -
          - value
          - seminar
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Tradeshow
        -
          - value
          - tradeshow
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Social Media'
        -
          - value
          - socialMedia
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'NeuroScience Website'
        -
          - value
          - neuroscienceWebsite
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Other
        -
          - value
          - other
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
