columnSuffix: null
contentColumnType: text
fieldGroup: 228fdc9a-5d24-44f0-89d9-fd7ddaf7524f # Patients
handle: hpcStoreFrontText
instructions: null
name: 'HPC Store Front Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 2
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
