columnSuffix: null
contentColumnType: string
fieldGroup: a8843661-a567-4e21-8928-2108d60edafe # Avatax
handle: lotNumbers
instructions: null
name: 'Lot numbers'
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    __assoc__:
      -
        - 97448ca3-d63e-46a6-a2b1-b2e4e1b93193 # Lot #
        -
          __assoc__:
            -
              - width
              - '20'
      -
        - 57aa7d91-dfe0-4596-bd52-8469cd1be41b # Description
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_lotnumbers}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: null
  staticField: null
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
