columnSuffix: null
contentColumnType: boolean
fieldGroup: 81b70b61-6757-484e-ace4-d9f92781c701 # Commerce
handle: makeThisARecurringOrder
instructions: ''
name: 'Make this a recurring order?'
searchable: false
settings:
  default: false
  offLabel: 'No'
  onLabel: 'Yes'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
