columnSuffix: null
contentColumnType: string
fieldGroup: c2f1cc8b-c74b-46fa-a18a-d11848cc3965 # Global Fields
handle: n0007Form
instructions: ''
name: 'N0007 Form'
searchable: true
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:b24cc19c-4033-41c8-b027-c8bde6ddb4c9' # Documents
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: 'Add document'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:b24cc19c-4033-41c8-b027-c8bde6ddb4c9' # Documents
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
