columnSuffix: null
contentColumnType: boolean
fieldGroup: aa06a404-5068-4c0d-9e2d-845531dba984 # Register Form
handle: n0011Terms
instructions: ''
name: 'N0011 Product Resale Agreement'
searchable: true
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
