columnSuffix: null
contentColumnType: string
fieldGroup: 4a7f50ea-95ad-4b62-a380-10a458ee6d34 # Mobile Application
handle: neuroselectOnlyLinkedAccount
instructions: ''
name: 'NeuroSelect Only Linked Account'
searchable: true
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: 'Select Connected Account'
  showSiteMenu: true
  source: null
  sources:
    - 'group:7bb97651-ed90-45bb-b144-6bcac199bfa8' # NeuroSelect Only
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Users
