columnSuffix: null
contentColumnType: text
fieldGroup: c229c28f-e6ca-4957-b7c5-b52c4d483452 # Text
handle: newAccountNote
instructions: null
name: 'New Account Note'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: 42413eea-7d73-4c19-ba3d-37a4d3879182 # Simple
  columnType: text
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  showWordCount: false
  sourceEditingGroups: '*'
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
