columnSuffix: qnchbpma
contentColumnType: text
fieldGroup: c2f1cc8b-c74b-46fa-a18a-d11848cc3965 # Global Fields
handle: noDocFound
instructions: null
name: 'No Doc Found...'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: 42413eea-7d73-4c19-ba3d-37a4d3879182 # Simple
  columnType: text
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
