columnSuffix: null
contentColumnType: string
fieldGroup: 228fdc9a-5d24-44f0-89d9-fd7ddaf7524f # Patients
handle: patientAccount
instructions: ''
name: 'Patient Account'
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources:
    - 'group:7bb97651-ed90-45bb-b144-6bcac199bfa8' # NeuroSelect Only
    - 'group:e0e6611c-ec20-44b8-96ce-23e0fa0d253b' # Personal (PUP)
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Users
