columnSuffix: null
contentColumnType: string
fieldGroup: c2f1cc8b-c74b-46fa-a18a-d11848cc3965 # Global Fields
handle: phoneLinks
instructions: null
name: 'Phone Links'
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    162:
      __assoc__:
        -
          - width
          - ''
    163:
      __assoc__:
        -
          - width
          - ''
  contentTable: '{{%stc_phonelinks}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add a row'
  staticField: null
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
