columnSuffix: null
contentColumnType: text
fieldGroup: 81b70b61-6757-484e-ace4-d9f92781c701 # Commerce
handle: productNote
instructions: 'Note to display on product page and cart.'
name: 'Product note'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
