columnSuffix: null
contentColumnType: string
fieldGroup: 81b70b61-6757-484e-ace4-d9f92781c701 # Commerce
handle: productFields
instructions: null
name: 'Product Fields'
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    __assoc__:
      -
        - 467ded05-6258-4805-a2b0-32cda632ca17 # Short Description
        -
          __assoc__:
            -
              - width
              - ''
      -
        - b23b05ab-da4c-47d2-9828-40d2e30d3e75 # Product Images
        -
          __assoc__:
            -
              - width
              - ''
      -
        - c79d5e59-4ec0-43e9-afd4-04e3a7baeb55 # Recommended Use
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 081ffeb6-8979-47aa-b26a-2e7838fe63f3 # Additional Information
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 71a8b34f-03e0-4728-a681-0262c3f3d678 # Resources
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 500a7cec-b4df-4fd4-a121-e4b16f760689 # Spec Sheet
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_productfields}}'
  fieldLayout: row
  maxRows: 1
  minRows: 1
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: content
  staticField: null
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
