columnSuffix: null
contentColumnType: string
fieldGroup: aa06a404-5068-4c0d-9e2d-845531dba984 # Register Form
handle: providerAsA
instructions: ''
name: 'Customer is a health care provider as a '
searchable: true
settings:
  byteLimit: null
  charLimit: '100'
  code: false
  columnType: string
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
