columnSuffix: null
contentColumnType: string
fieldGroup: 4a7f50ea-95ad-4b62-a380-10a458ee6d34 # Mobile Application
handle: qrScanTable
instructions: null
name: 'QR Scan Table'
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    __assoc__:
      -
        - 284
        -
          __assoc__:
            -
              - width
              - '50'
      -
        - 291
        -
          __assoc__:
            -
              - width
              - '50'
      -
        - 285
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 286
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 287
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 288
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 289
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 290
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_qrscantable}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add a row'
  staticField: null
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
