columnSuffix: null
contentColumnType: boolean
fieldGroup: aa06a404-5068-4c0d-9e2d-845531dba984 # Register Form
handle: receiveUpdates
instructions: ''
name: 'Receive Updates'
searchable: true
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
