columnSuffix: yrwocylf
contentColumnType: boolean
fieldGroup: 9fd48f5f-c27d-4d13-b181-47a720fb98c6 # Default
handle: recommendationViewed
instructions: ''
name: 'Recommendation Viewed?'
searchable: false
settings:
  default: false
  offLabel: 'No'
  onLabel: 'Yes'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
