columnSuffix: null
contentColumnType: text
fieldGroup: 96355652-fd03-4961-9979-624730faaa91 # Categories
handle: references
instructions: null
name: References
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: 42413eea-7d73-4c19-ba3d-37a4d3879182 # Simple
  columnType: text
  defaultTransform: null
  purifierConfig: null
  purifyHtml: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  showWordCount: false
  sourceEditingGroups: '*'
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
