columnSuffix: null
contentColumnType: text
fieldGroup: 96355652-fd03-4961-9979-624730faaa91 # Categories
handle: references
instructions: null
name: References
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: 45ee12db-a387-4bf5-bf41-95d8744b1ffa # Simple
  columnType: text
  defaultTransform: null
  purifierConfig: null
  purifyHtml: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  showWordCount: false
  sourceEditingGroups: '*'
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
