columnSuffix: null
contentColumnType: text
fieldGroup: aa06a404-5068-4c0d-9e2d-845531dba984 # Register Form
handle: registrationCertificationLicense
instructions: ''
name: 'Registration, Certification, License #'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
