columnSuffix: null
contentColumnType: string
fieldGroup: 81b70b61-6757-484e-ace4-d9f92781c701 # Commerce
handle: relatedProducts
instructions: null
name: 'Related Products'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 4
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\commerce\fields\Products
