columnSuffix: null
contentColumnType: text
fieldGroup: c229c28f-e6ca-4957-b7c5-b52c4d483452 # Text
handle: salesRepSearch
instructions: null
name: 'Sales Rep Search'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: 45ee12db-a387-4bf5-bf41-95d8744b1ffa # Simple
  columnType: text
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  showWordCount: false
  sourceEditingGroups: '*'
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
