columnSuffix: null
contentColumnType: text
fieldGroup: c229c28f-e6ca-4957-b7c5-b52c4d483452 # Text
handle: salesRepSearch
instructions: null
name: 'Sales Rep Search'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  redactorConfig: Standard.json
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showHtmlButtonForNonAdmins: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
