columnSuffix: null
contentColumnType: string
fieldGroup: aa06a404-5068-4c0d-9e2d-845531dba984 # Register Form
handle: secretQuestion
instructions: null
name: 'Secret Question'
searchable: true
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - 'What is your mother''s maiden name?'
        -
          - value
          - whatIsYourMothersMaidenName
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'What is your father''s middle name?'
        -
          - value
          - whatIsYourFathersMiddleName
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'What is your oldest sibling''s name?'
        -
          - value
          - whatIsYourOldestSiblingsName
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'What is the name of your first pet?'
        -
          - value
          - whatIsTheNameOfYourFirstPet
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
