columnSuffix: yqqconrt
contentColumnType: text
fieldGroup: 81b70b61-6757-484e-ace4-d9f92781c701 # Commerce
handle: seoOptions
instructions: ''
name: 'SEO Options'
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoPreview
    - mainEntityOfPage
    - seoTitle
    - siteNamePosition
    - seoDescription
    - seoKeywords
    - seoImage
    - seoImageTransform
    - seoImageTransformMode
    - seoImageDescription
    - robots
    - canonicalUrl
  generalTabEnabled: '1'
  sitemapTabEnabled: ''
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
