columnSuffix: null
contentColumnType: text
fieldGroup: 6329f165-1216-4dee-8071-071c8c5cb854 # Comparison table
handle: shortDescription
instructions: null
name: 'Short Description'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  characterLimit: null
  ckeConfig: 45ee12db-a387-4bf5-bf41-95d8744b1ffa # Simple
  columnType: text
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
