columnSuffix: null
contentColumnType: string
fieldGroup: 4a7f50ea-95ad-4b62-a380-10a458ee6d34 # Mobile Application
handle: sleepSubmission
instructions: null
name: 'Sleep Submission'
searchable: true
settings:
  blockTypeFields: 0
  changedFieldIndicator: null
  columns:
    __assoc__:
      -
        - new1
        -
          __assoc__:
            -
              - width
              - ''
      -
        - new2
        -
          __assoc__:
            -
              - width
              - ''
      -
        - new3
        -
          __assoc__:
            -
              - width
              - ''
      -
        - new4
        -
          __assoc__:
            -
              - width
              - ''
      -
        - new5
        -
          __assoc__:
            -
              - width
              - ''
      -
        - new6
        -
          __assoc__:
            -
              - width
              - ''
      -
        - new7
        -
          __assoc__:
            -
              - width
              - ''
      -
        - new8
        -
          __assoc__:
            -
              - width
              - ''
      -
        - new9
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_sleepsubmission}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: 'Add a row'
  staticField: null
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
