columnSuffix: null
contentColumnType: text
fieldGroup: 9fd48f5f-c27d-4d13-b181-47a720fb98c6 # Default
handle: subHeading
instructions: null
name: Sub-heading
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
