field: 4ee14c7e-9bf2-4692-a2ee-5887f40566de # PIR Key Ingredients
fieldLayouts:
  7958943d-6926-4aba-a849-ba844c185d67:
    tabs:
      -
        elements:
          -
            fieldUid: b372ea6c-d2a2-4e45-9c7a-3b12f1cbd4d1 # Ingredient
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6d46cc52-8b50-4cfb-99bc-14782782d963 # Description
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f872f3fa-1f1b-49c6-92cd-4b7ed39ef576 # References
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6d46cc52-8b50-4cfb-99bc-14782782d963: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: ''
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  b372ea6c-d2a2-4e45-9c7a-3b12f1cbd4d1: # Ingredient
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: ingredient
    instructions: ''
    name: Ingredient
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f872f3fa-1f1b-49c6-92cd-4b7ed39ef576: # References
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: references
    instructions: ''
    name: References
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: ''
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
