changedFieldIndicator: null
field: 05604439-6c5c-41e1-acac-f9f2e807fbbb # Accordion
fieldLayouts:
  50941910-a816-406b-b010-98c87cc56470:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9f228eee-1e7f-4f4d-aaab-45ced2112783 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a76486ab-de48-48cb-81d2-cb83c9cff7a9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8e6ec6f8-d9bb-4336-b939-97523357eeee # Drawer Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12bc45f3-0521-4a9e-a67e-77fce998647a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7a64e39b-5c15-4a93-a8ba-29d26c4f23a6
        userCondition: null
fields:
  8e6ec6f8-d9bb-4336-b939-97523357eeee: # Drawer Content
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: drawerContent
    instructions: null
    name: 'Drawer Content'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 45ee12db-a387-4bf5-bf41-95d8744b1ffa # Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      showWordCount: false
      sourceEditingGroups: '*'
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  9f228eee-1e7f-4f4d-aaab-45ced2112783: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
