field: 913b6a3c-8469-4974-bf89-f32df7541a75 # Clinical Indication Submission
fieldLayouts:
  0699e575-da8a-4170-be54-935d8b366802:
    tabs:
      -
        elements:
          -
            fieldUid: b3efe8d7-ee54-4ac8-a3bd-a2c20b0bd63e # ID
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fd5f45be-0453-4608-b9d1-24de4f1c4a25 # Date
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2f08d814-a695-4dfa-bec4-e3c7454d337d # Clinical Indicators
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 149ee959-b169-4ec3-9751-ebef74678f35 # Category
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0e1cc5ca-e027-4cab-8509-b20ccdf56493 # Age
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 98d51a26-0b21-40a5-9997-8d6f86773a52 # Gender
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7aec2441-a928-4ca5-9115-b26ca863bac0 # PDF Generated
            instructions: null
            label: null
            required: 0
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0e1cc5ca-e027-4cab-8509-b20ccdf56493: # Age
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: age
    instructions: ''
    name: Age
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2f08d814-a695-4dfa-bec4-e3c7454d337d: # Clinical Indicators
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: clinicalindicators
    instructions: ''
    name: 'Clinical Indicators'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7aec2441-a928-4ca5-9115-b26ca863bac0: # PDF Generated
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: pdfGenerated
    instructions: ''
    name: 'PDF Generated'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  98d51a26-0b21-40a5-9997-8d6f86773a52: # Gender
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: gender
    instructions: ''
    name: Gender
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  149ee959-b169-4ec3-9751-ebef74678f35: # Category
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: category
    instructions: ''
    name: Category
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b3efe8d7-ee54-4ac8-a3bd-a2c20b0bd63e: # ID
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: submissionId
    instructions: ''
    name: ID
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fd5f45be-0453-4608-b9d1-24de4f1c4a25: # Date
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: date
    instructions: ''
    name: Date
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
