changedFieldIndicator: null
field: b0b0037d-3e09-47c0-a685-339635407c57 # Contact Tiles
fieldLayouts:
  8b677aee-7256-4daa-9d2d-18ba06ab5f90:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7024b210-f463-4600-9ac7-05625e3883f6 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 940571e7-9fbb-4aa4-a900-cf397abac78e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7528b442-be60-430f-b0cc-020db103633a # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f063ab3-f893-4fb4-b9d3-89e3f6ff2312
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b59e4497-6d6b-4c2b-a77e-11c197e02a07 # Hours of Operation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5801f48d-e1e9-43c0-bf3f-60e678331247
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6edadbad-87ae-4215-9fc3-f66a52c1182b # Phone Number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fd59bc9-3a45-4c2f-9ba6-e4131b830241
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 175237b9-6eeb-4dbf-9db8-90e23c0f1eeb # Email Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28a3be40-5d91-49e4-a975-18ac109a6522
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 84930ff9-6399-4255-96ec-c812788e899d # Fax
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 978c149f-85af-47da-98b5-aa1148e5f237
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8187a7e0-4154-4f90-8e1c-f1a9f19291f0 # Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6469d32-770e-43c6-a7c8-a0ff374b4f18
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 20b28742-b392-4b9f-9203-1fff3a5a6ba3
        userCondition: null
fields:
  6edadbad-87ae-4215-9fc3-f66a52c1182b: # Phone Number
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: phoneNumber
    instructions: null
    name: 'Phone Number'
    searchable: true
    settings:
      allowCustomText: true
      allowTarget: true
      defaultText: null
      selectLinkText: ''
      types:
        __assoc__:
          -
            - presseddigital\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - 1
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\linkit\fields\LinkitField
  7024b210-f463-4600-9ac7-05625e3883f6: # Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: null
    name: Icon
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  7528b442-be60-430f-b0cc-020db103633a: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8187a7e0-4154-4f90-8e1c-f1a9f19291f0: # Address
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: address
    instructions: null
    name: Address
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 42413eea-7d73-4c19-ba3d-37a4d3879182 # Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      showWordCount: false
      sourceEditingGroups: '*'
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  84930ff9-6399-4255-96ec-c812788e899d: # Fax
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: fax
    instructions: null
    name: Fax
    searchable: true
    settings:
      allowCustomText: true
      allowTarget: true
      defaultText: null
      selectLinkText: ''
      types:
        __assoc__:
          -
            - presseddigital\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - 1
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\linkit\fields\LinkitField
  175237b9-6eeb-4dbf-9db8-90e23c0f1eeb: # Email Address
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: emailAddress
    instructions: null
    name: 'Email Address'
    searchable: true
    settings:
      allowCustomText: true
      allowTarget: true
      defaultText: null
      selectLinkText: ''
      types:
        __assoc__:
          -
            - presseddigital\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - 1
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\linkit\fields\LinkitField
  b59e4497-6d6b-4c2b-a77e-11c197e02a07: # Hours of Operation
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: hoursOfOperation
    instructions: null
    name: 'Hours of Operation'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
