changedFieldIndicator: null
field: 55fae896-2a87-4393-aa94-39432a7c2675 # Image Blocks
fieldLayouts:
  1d16cc7b-d5d1-46a6-9faa-ca10eeacdf42:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 767de218-132f-4122-900d-7a5f99077bac # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 045e9251-96e5-4dbf-99df-78f211f46e81
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c2462d51-88ed-4bee-b2a6-c14165c03ef5 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25d6fc18-23d1-49c2-b7c8-74988d79fd20
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c952442c-2c32-4f37-b77f-efe94bc2fc45 # Sub Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f5cdcd7-9120-413f-9176-d79b1d3424bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 27319cf4-365d-4ab0-9f37-bdeb90374f33 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b4d7b45-0ae0-42d5-9f98-1ecfe6ad7749
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8b19a1c0-f3dc-4a5a-bf29-661ca5043f6c
        userCondition: null
fields:
  767de218-132f-4122-900d-7a5f99077bac: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  27319cf4-365d-4ab0-9f37-bdeb90374f33: # Color
    columnSuffix: null
    contentColumnType: char(7)
    fieldGroup: null
    handle: color
    instructions: null
    name: Color
    searchable: true
    settings:
      defaultColor: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  c2462d51-88ed-4bee-b2a6-c14165c03ef5: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c952442c-2c32-4f37-b77f-efe94bc2fc45: # Sub Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: subHeadline
    instructions: null
    name: 'Sub Headline'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
