changedFieldIndicator: null
field: c6a86332-cec0-423e-a200-4b3de8509a95 # Key Ingredients
fieldLayouts:
  1ec76e07-17df-4882-81ad-f3999af82377:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 32faaac3-a839-4748-aa11-945c9ee98336 # Ingredients
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2383d2c-177f-4616-8255-3a5ad636f687
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8a9a811a-3a61-4edf-b448-213fd07541d0 # Precursor Potential
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e52bfec3-bd2a-454b-bc3b-e6ab2ab5e0f8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0be19f7a-fb9f-4878-ad05-3e654bf46d56
        userCondition: null
fields:
  8a9a811a-3a61-4edf-b448-213fd07541d0: # Precursor Potential
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: precursorPotential
    instructions: null
    name: 'Precursor Potential'
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - ''
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Checked
            -
              - value
              - checked
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Mild - UP'
            -
              - value
              - mildUp
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Moderate - UP'
            -
              - value
              - moderateUp
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Strong - UP'
            -
              - value
              - strongUp
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Mild - Down'
            -
              - value
              - mildDown
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Moderate - Down'
            -
              - value
              - moderateDown
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Strong - Down'
            -
              - value
              - strongDown
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  32faaac3-a839-4748-aa11-945c9ee98336: # Ingredients
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: ingredients
    instructions: null
    name: Ingredients
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Cortisol
            -
              - value
              - cortisol
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Melatonin
            -
              - value
              - melatonin
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
