changedFieldIndicator: null
field: e697251b-8d8c-4911-ba14-486479a207a9 # Clinical Indicators Table
fieldLayouts:
  fd40e5c5-433f-44a3-ace2-ef3560049366:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 130b86fd-43ec-46b6-b161-fca9e3a1ebce # Clinical Symptoms
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd3129bd-03a6-4b5b-a724-f970679076d5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 75be2701-eb22-4d93-8669-85d837ffa402 # Associated Product
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5272b3e5-0377-455d-88fc-81240f2492c5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 089c96c7-150c-49e6-9e6e-cc5a82eef4e1 # Age
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2058516-c4ee-449d-a723-cfa6fd55450a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cd620454-bac9-4cbb-946d-c91e533d2372 # Age Check
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae320e31-9b15-4cae-9ff6-1511fbd0cffa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dbecde4e-9b37-4570-9322-33bdc3b18b9f # Immune/ Adrenal
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1668e3ba-2e26-47b0-91f6-c67838c0206d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1e48e454-26ad-43ee-8d7d-13de378a5c17
        userCondition: null
fields:
  75be2701-eb22-4d93-8669-85d837ffa402: # Associated Product
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: associatedProduct
    instructions: null
    name: 'Associated Product'
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\commerce\fields\Products
  089c96c7-150c-49e6-9e6e-cc5a82eef4e1: # Age
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: age
    instructions: null
    name: Age
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Not specified'
            -
              - value
              - notSpecified
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 13+
            -
              - value
              - '13'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 12-
            -
              - value
              - '12'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  130b86fd-43ec-46b6-b161-fca9e3a1ebce: # Clinical Symptoms
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: clinicalSymptoms
    instructions: null
    name: 'Clinical Symptoms'
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: true
      maxRelations: null
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      source: 'group:f5844837-8d59-43fe-9cb8-765af3f4ff51' # Clinical Symptoms
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  cd620454-bac9-4cbb-946d-c91e533d2372: # Age Check
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: ageCheck
    instructions: null
    name: 'Age Check'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  dbecde4e-9b37-4570-9322-33bdc3b18b9f: # Immune/ Adrenal
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: immuneAdrenal
    instructions: null
    name: 'Immune/ Adrenal'
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Not specified'
            -
              - value
              - notSpecified
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Immune
            -
              - value
              - immune
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Adrenal
            -
              - value
              - adrenal
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
