changedFieldIndicator: null
field: 29f04a5b-7cef-482b-94f3-66a0cdc010a8 # CTA Tiles
fieldLayouts:
  b66322e7-2414-4415-8ed5-026218929ba6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 06cb98a9-fc79-4e72-9170-3609a6c7b347 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 805ea729-ca27-4e8b-91c0-ab00354d5399
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cecc2765-1f52-4dc8-b85d-cc8a51ac6bdc # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0712a53-b2e7-41c4-84c5-d137d079c3f6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d69fddcb-416a-4178-abae-a4cb54913272 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f33f11b-fe89-4149-a624-bf66805cc093
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4c7a2b70-0e27-4e2c-9b04-16efe8fc2edc # CTA
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2f20c15-50ba-477a-ab21-130145d1fed3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 767fa68d-093e-46e4-b7ef-3bb453f5b04b # Tile?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 336140f4-37a2-46de-89fa-b14b936f1ea8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fda49ad1-e4ec-484a-a94c-05df740c0530
        userCondition: null
fields:
  4c7a2b70-0e27-4e2c-9b04-16efe8fc2edc: # CTA
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: cta
    instructions: null
    name: CTA
    searchable: true
    settings:
      allowCustomText: true
      allowTarget: true
      defaultText: null
      selectLinkText: ''
      types:
        __assoc__:
          -
            - presseddigital\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
                -
                  - allowAlias
                  - '1'
                -
                  - allowMailto
                  - '1'
                -
                  - allowHash
                  - '1'
                -
                  - allowPaths
                  - '1'
          -
            - presseddigital\linkit\models\Twitter
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Facebook
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Instagram
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\LinkedIn
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - presseddigital\linkit\models\Entry
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select an entry'
          -
            - presseddigital\linkit\models\Category
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select a category'
          -
            - presseddigital\linkit\models\Asset
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select an asset'
          -
            - presseddigital\linkit\models\User
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
                -
                  - userPath
                  - ''
          -
            - presseddigital\linkit\models\Product
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select an entry'
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\linkit\fields\LinkitField
  06cb98a9-fc79-4e72-9170-3609a6c7b347: # Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: null
    name: Icon
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  767fa68d-093e-46e4-b7ef-3bb453f5b04b: # Tile?
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: tile
    instructions: null
    name: 'Tile?'
    searchable: true
    settings:
      default: true
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  cecc2765-1f52-4dc8-b85d-cc8a51ac6bdc: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d69fddcb-416a-4178-abae-a4cb54913272: # Body
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: body
    instructions: null
    name: Body
    searchable: true
    settings:
      errorMessage: 'Unable to find component class ''craft\redactor\Field''.'
      expectedType: craft\redactor\Field
      settings:
        __assoc__:
          -
            - availableTransforms
            - '*'
          -
            - availableVolumes
            - '*'
          -
            - columnType
            - text
          -
            - configSelectionMode
            - choose
          -
            - defaultTransform
            - ''
          -
            - manualConfig
            - ''
          -
            - purifierConfig
            - ''
          -
            - purifyHtml
            - '1'
          -
            - redactorConfig
            - ''
          -
            - removeEmptyTags
            - '1'
          -
            - removeInlineStyles
            - '1'
          -
            - removeNbsp
            - '1'
          -
            - showHtmlButtonForNonAdmins
            - '1'
          -
            - showUnpermittedFiles
            - false
          -
            - showUnpermittedVolumes
            - true
          -
            - uiMode
            - enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MissingField
