changedFieldIndicator: null
field: 334b094b-e2f3-4ede-a38f-667378ae3d9c # QR Scan Submissions
fieldLayouts:
  95738e61-f603-4e3e-a2d3-4b845b75abec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1494120d-5382-4a39-ab20-eda95189eb8b # ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ce765aa-db4d-418f-a0ec-0b1d2933e5bc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 36a53fab-5ce1-4a7d-bee3-72939426ff8d # Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52b7ff21-da95-4c7a-917b-566c1d4aef7c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 68ed3805-7765-40d4-91ed-14adbf0c9f24 # Data
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2342805f-d4e4-4be1-bf78-66f7d7bad269
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1065e241-1779-49e7-984b-5604c0355f65 # Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90c5856f-7d53-48a0-a12e-2641ffe50cfe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f8b329e7-2c51-419c-b1d4-58afb77f0b95 # PDF Generated
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d20ffb2-f17b-4198-9db2-85fdb04508b5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1bf18fd5-e735-4124-990e-0db232b07a95
        userCondition: null
fields:
  36a53fab-5ce1-4a7d-bee3-72939426ff8d: # Date
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: date
    instructions: null
    name: Date
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  68ed3805-7765-40d4-91ed-14adbf0c9f24: # Data
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: data
    instructions: null
    name: Data
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  1065e241-1779-49e7-984b-5604c0355f65: # Category
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: category
    instructions: null
    name: Category
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  1494120d-5382-4a39-ab20-eda95189eb8b: # ID
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: submissionId
    instructions: null
    name: ID
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f8b329e7-2c51-419c-b1d4-58afb77f0b95: # PDF Generated
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: pdfGenerated
    instructions: null
    name: 'PDF Generated'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
