changedFieldIndicator: null
field: cfbe0147-1cfa-4cbd-a0a2-42dfb7278536 # Product Submission
fieldLayouts:
  10b5ccef-ed59-489b-8483-ac44c2a8d688:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d2f95df2-89ea-43b8-b84d-0e937ee47715 # ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3bd25658-b9a7-449c-80a3-91a1ef43662e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c90899ec-f418-4c3a-88c4-ab2d5ad78a9c # Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 042dc23e-3e18-4fee-b84c-c10ee8e753b0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 13a41bcb-8067-42ec-b258-9b6704d154f5 # Products
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96215a75-a158-437c-b433-dbecf3b0a4b8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8e5f4c47-beb0-4ec2-b5ad-56803a4cadec # Age
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ff714a5-e10d-4d1a-8324-c45ddfd0632a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 213d7db1-82b4-4083-8c16-e9c869c87f1c # Gender
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45952bb8-b803-47a9-8a6f-08c25d78f930
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c0157df9-eb24-42fb-b900-cbbe439d951e # PDF Generated
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6571837-519d-4573-862e-ee0de25c9488
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 21d0a1de-2272-4365-9312-429872179b29
        userCondition: null
fields:
  8e5f4c47-beb0-4ec2-b5ad-56803a4cadec: # Age
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: age
    instructions: null
    name: Age
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  13a41bcb-8067-42ec-b258-9b6704d154f5: # Products
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: products
    instructions: null
    name: Products
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  213d7db1-82b4-4083-8c16-e9c869c87f1c: # Gender
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: gender
    instructions: null
    name: Gender
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c0157df9-eb24-42fb-b900-cbbe439d951e: # PDF Generated
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: pdfGenerated
    instructions: null
    name: 'PDF Generated'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  c90899ec-f418-4c3a-88c4-ab2d5ad78a9c: # Date
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: date
    instructions: null
    name: Date
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d2f95df2-89ea-43b8-b84d-0e937ee47715: # ID
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: submissionId
    instructions: null
    name: ID
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
