field: 465b7c35-c93e-4d9f-ab1d-b25bf2915bcd # Sales Reps
fieldLayouts:
  d25cbe7f-d6f0-4a4b-b9b1-a111a808b08a:
    tabs:
      -
        elements:
          -
            fieldUid: 8c554832-84e2-4539-aff9-2bb81dcdf9cb # Headshot
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 59c64a2c-277d-44ff-9353-009292105a82 # Phone #
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6c31e057-1749-4bb2-9ee4-0ac2c38f7e0c # Email
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e5391192-5b85-4f09-8f42-f11e09a52743 # About
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6c31e057-1749-4bb2-9ee4-0ac2c38f7e0c: # Email
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: email
    instructions: ''
    name: Email
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8c554832-84e2-4539-aff9-2bb81dcdf9cb: # Headshot
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: headshot
    instructions: ''
    name: Headshot
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  59c64a2c-277d-44ff-9353-009292105a82: # Phone #
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: phone
    instructions: ''
    name: 'Phone #'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e5391192-5b85-4f09-8f42-f11e09a52743: # About
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: about
    instructions: ''
    name: About
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
