changedFieldIndicator: null
field: 465b7c35-c93e-4d9f-ab1d-b25bf2915bcd # Sales Reps
fieldLayouts:
  d25cbe7f-d6f0-4a4b-b9b1-a111a808b08a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8c554832-84e2-4539-aff9-2bb81dcdf9cb # Headshot
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7fd8225-08be-4e67-a926-04b27c74ecc8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 59c64a2c-277d-44ff-9353-009292105a82 # Phone #
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4ab26c8-5f5b-4543-ab2d-c182ecf2a031
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c31e057-1749-4bb2-9ee4-0ac2c38f7e0c # Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b2686bc-5ed0-412b-b07b-a292c7c5e720
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5391192-5b85-4f09-8f42-f11e09a52743 # About
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bd982b97-65bb-4814-9e8f-e3f4b0b67a4e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2d1053e2-8565-4f65-b079-5ad4f3acda6b
        userCondition: null
fields:
  6c31e057-1749-4bb2-9ee4-0ac2c38f7e0c: # Email
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: email
    instructions: null
    name: Email
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8c554832-84e2-4539-aff9-2bb81dcdf9cb: # Headshot
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: headshot
    instructions: null
    name: Headshot
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  59c64a2c-277d-44ff-9353-009292105a82: # Phone #
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: phone
    instructions: null
    name: 'Phone #'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e5391192-5b85-4f09-8f42-f11e09a52743: # About
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: about
    instructions: null
    name: About
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      ckeConfig: 3c7d8a91-2b4e-4f63-9c1d-8e5f6a7b9c0d # Standard
      columnType: text
      defaultTransform: ''
      enableSourceEditingForNonAdmins: true
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
