changedFieldIndicator: null
field: 465b7c35-c93e-4d9f-ab1d-b25bf2915bcd # Sales Reps
fieldLayouts:
  d25cbe7f-d6f0-4a4b-b9b1-a111a808b08a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8c554832-84e2-4539-aff9-2bb81dcdf9cb # Headshot
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf5ec572-194e-4d23-9da5-d7142dd65c40
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 59c64a2c-277d-44ff-9353-009292105a82 # Phone #
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 420d1d4c-fb28-4df3-a942-5269609ead48
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c31e057-1749-4bb2-9ee4-0ac2c38f7e0c # Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b892fb14-c570-4d5f-8a1d-91673f0a37c9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e5391192-5b85-4f09-8f42-f11e09a52743 # About
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b95e7e12-1df5-487c-8328-d341548a331c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1ea04f5e-eefa-41b2-b74f-175a49c4b99a
        userCondition: null
fields:
  6c31e057-1749-4bb2-9ee4-0ac2c38f7e0c: # Email
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: email
    instructions: null
    name: Email
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8c554832-84e2-4539-aff9-2bb81dcdf9cb: # Headshot
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: headshot
    instructions: null
    name: Headshot
    searchable: true
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:4dfe4bea-c93a-4f15-be8b-20bd2693323e' # Images
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  59c64a2c-277d-44ff-9353-009292105a82: # Phone #
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: phone
    instructions: null
    name: 'Phone #'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e5391192-5b85-4f09-8f42-f11e09a52743: # About
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: about
    instructions: null
    name: About
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 45ee12db-a387-4bf5-bf41-95d8744b1ffa # Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      showWordCount: false
      sourceEditingGroups: '*'
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
