changedFieldIndicator: null
field: 693887d6-503f-479e-b676-b2f548ab5367 # Pathways Table
fieldLayouts:
  4d05b114-a39b-4b11-b7ac-9a7c3a8fb66a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8dce5136-1481-4d42-aadf-1fb0e7c92b01 # Neurotransmitters
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18d3713d-1052-491f-a57e-4a1ad26acc2e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7585d33d-c39f-4bc6-b4d2-3ef21a2ae3c2 # Associated Product
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54c302dc-2d64-4122-a578-b1dc7d1d47f0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cdf57f41-5c12-4ece-9c09-c2b317af2b39 # Age
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f17214be-43c2-4cc4-8412-6728419463a6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 961d042b-759e-43e9-a6f9-1f088df64420 # Age Check
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 568065e7-5eb9-41b3-af61-4580e732aa93
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5b02b6d5-d94f-49ce-80e2-74421665799e # Immune/ Adrenal
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c97097a-b24f-42aa-b74c-a91287a4d315
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f53c8f6e-07dc-4950-993f-39642dadc8aa
        userCondition: null
fields:
  5b02b6d5-d94f-49ce-80e2-74421665799e: # Immune/ Adrenal
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: immuneAdrenal
    instructions: null
    name: 'Immune/ Adrenal'
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Not specified'
            -
              - value
              - notSpecified
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Immune
            -
              - value
              - immune
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Adrenal
            -
              - value
              - adrenal
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  8dce5136-1481-4d42-aadf-1fb0e7c92b01: # Neurotransmitters
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: neurotransmitters
    instructions: null
    name: Neurotransmitters
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: true
      maxRelations: null
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      source: 'group:f7a04aca-b458-463e-ac40-4e70fe38fe09' # QR Scan Pathways
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  961d042b-759e-43e9-a6f9-1f088df64420: # Age Check
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: ageCheck
    instructions: null
    name: 'Age Check'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  7585d33d-c39f-4bc6-b4d2-3ef21a2ae3c2: # Associated Product
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: associatedProduct
    instructions: null
    name: 'Associated Product'
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\commerce\fields\Products
  cdf57f41-5c12-4ece-9c09-c2b317af2b39: # Age
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: age
    instructions: null
    name: Age
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Not specified'
            -
              - value
              - notSpecified
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 13+
            -
              - value
              - '13'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 12-
            -
              - value
              - '12'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
