changedFieldIndicator: null
field: 6155050f-240b-4ccc-9afc-095f7b936e55 # Social Links
fieldLayouts:
  1b28d3ff-3086-4448-924b-486396734f1e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3c1e103a-5e56-4e37-994e-6ae6a7e4101f # Facebook Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4cc9c27c-ee37-4d74-8e1f-65ce08a01644
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4328bdab-17ae-4784-afa2-f6a596c482d2 # LinkedIn Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dbae54a3-d6d9-4e73-9f51-3f238dece793
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 543dfba1-a252-4ba2-abad-cd4c1af0409d # Twitter Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f75af95f-fba0-438b-9aad-adb80e33358e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f88b8399-a224-4f0b-8fc0-d59df2d28f1a # Youtube Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0733562a-9947-44fb-8893-da8e59394df7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4d3c3f6a-36ab-4da9-9e37-4a58fbce22a7 # Instagram URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abc1df66-bc59-4980-be37-337b4956b388
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6bbb756d-2efe-482a-8d64-4c95c9150e17
        userCondition: null
fields:
  3c1e103a-5e56-4e37-994e-6ae6a7e4101f: # Facebook Url
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: facebookUrl
    instructions: null
    name: 'Facebook Url'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4d3c3f6a-36ab-4da9-9e37-4a58fbce22a7: # Instagram URL
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: instagramUrl
    instructions: null
    name: 'Instagram URL'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  543dfba1-a252-4ba2-abad-cd4c1af0409d: # Twitter Url
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: twitterUrl
    instructions: null
    name: 'Twitter Url'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4328bdab-17ae-4784-afa2-f6a596c482d2: # LinkedIn Url
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: linkedinUrl
    instructions: null
    name: 'LinkedIn Url'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f88b8399-a224-4f0b-8fc0-d59df2d28f1a: # Youtube Url
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: youtubeUrl
    instructions: null
    name: 'Youtube Url'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
