changedFieldIndicator: null
field: 018dc23e-786f-4cd7-947c-cffd6a3a3409 # Key Ingredients
fieldLayouts:
  d2913031-ff2f-4beb-9631-ac56d64aba6e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c4d1187f-273c-4532-a72a-09801d5c80d1 # Ingredients
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bcf127d8-f224-4323-9e1a-5369ed075781
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c0911def-59e3-4a6e-adac-c063e43a0cbf # Precursor Potential
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83db6833-0d78-4903-b00f-5cb171583da2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 12eef4f2-53a7-4930-9d35-0ea7b807e6d9
        userCondition: null
fields:
  c0911def-59e3-4a6e-adac-c063e43a0cbf: # Precursor Potential
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: precursorPotential
    instructions: null
    name: 'Precursor Potential'
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - ''
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Checked
            -
              - value
              - checked
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Mild - UP'
            -
              - value
              - mildUp
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Moderate - UP'
            -
              - value
              - moderateUp
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Strong - UP'
            -
              - value
              - strongUp
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Mild - Down'
            -
              - value
              - mildDown
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Moderate - Down'
            -
              - value
              - moderateDown
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Strong - Down'
            -
              - value
              - strongDown
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c4d1187f-273c-4532-a72a-09801d5c80d1: # Ingredients
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: ingredients
    instructions: null
    name: Ingredients
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Serotonin
            -
              - value
              - serotonin
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - GABA
            -
              - value
              - gaba
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Taurine
            -
              - value
              - taurine
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Glutamate
            -
              - value
              - glutamate
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - PEA
            -
              - value
              - pea
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dopamine
            -
              - value
              - dopamine
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Norepinephrine
            -
              - value
              - norepinephrine
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Epinephrine
            -
              - value
              - epinephrine
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Acetylcholine
            -
              - value
              - acetylcholine
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
