changedFieldIndicator: null
field: 1e3887a1-7daa-4ba7-898d-caa7ada6fd6f # Product Survey Details
fieldLayouts:
  bdab86ef-f836-4201-bf72-011daf696d20:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c48523f4-650a-45fa-b015-6c0d09c1c94a # Sleep content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6cbad4e-660c-4935-9a66-183426747d95
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 989e8fee-a375-4704-b002-91f68bccec4e # Stress content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aac67b67-5de1-4fa1-aa71-033faf5dca7a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 381461cb-47ce-40ff-a867-938e0e94a64f # Fatigue content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93bd8e79-d9fa-44a2-9d00-5b9cd95ce14c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4db43d9f-b5cd-4243-98bf-373a7e2a013e
        userCondition: null
fields:
  989e8fee-a375-4704-b002-91f68bccec4e: # Stress content
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: stressContent
    instructions: null
    name: 'Stress content'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 45ee12db-a387-4bf5-bf41-95d8744b1ffa # Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      sourceEditingGroups:
        - __ADMINS__
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  381461cb-47ce-40ff-a867-938e0e94a64f: # Fatigue content
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: fatigueContent
    instructions: null
    name: 'Fatigue content'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 45ee12db-a387-4bf5-bf41-95d8744b1ffa # Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      sourceEditingGroups:
        - __ADMINS__
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  c48523f4-650a-45fa-b015-6c0d09c1c94a: # Sleep content
    columnSuffix: null
    contentColumnType: mediumtext
    fieldGroup: null
    handle: sleepContent
    instructions: null
    name: 'Sleep content'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 45ee12db-a387-4bf5-bf41-95d8744b1ffa # Simple
      columnType: mediumtext
      defaultTransform: null
      purifierConfig: null
      purifyHtml: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      sourceEditingGroups:
        - __ADMINS__
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
