changedFieldIndicator: null
field: 1e3887a1-7daa-4ba7-898d-caa7ada6fd6f # Product Survey Details
fieldLayouts:
  bdab86ef-f836-4201-bf72-011daf696d20:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c48523f4-650a-45fa-b015-6c0d09c1c94a # Sleep content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab63c23a-f179-4cb9-8fb1-cdd41a404ace
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 989e8fee-a375-4704-b002-91f68bccec4e # Stress content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc9e570f-8e1e-4d91-bd90-ec6b8b768f7e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 381461cb-47ce-40ff-a867-938e0e94a64f # Fatigue content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53eb286e-aa07-4d27-b1ca-ff2144aa854e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9da02316-8c58-481d-8f54-20d8a81b359d
        userCondition: null
fields:
  989e8fee-a375-4704-b002-91f68bccec4e: # Stress content
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: stressContent
    instructions: null
    name: 'Stress content'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 42413eea-7d73-4c19-ba3d-37a4d3879182 # Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      sourceEditingGroups:
        - __ADMINS__
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  381461cb-47ce-40ff-a867-938e0e94a64f: # Fatigue content
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: fatigueContent
    instructions: null
    name: 'Fatigue content'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 42413eea-7d73-4c19-ba3d-37a4d3879182 # Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      sourceEditingGroups:
        - __ADMINS__
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  c48523f4-650a-45fa-b015-6c0d09c1c94a: # Sleep content
    columnSuffix: null
    contentColumnType: mediumtext
    fieldGroup: null
    handle: sleepContent
    instructions: null
    name: 'Sleep content'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 42413eea-7d73-4c19-ba3d-37a4d3879182 # Simple
      columnType: mediumtext
      defaultTransform: null
      purifierConfig: null
      purifyHtml: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      sourceEditingGroups:
        - __ADMINS__
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
