changedFieldIndicator: null
field: 5aef1b3e-1992-4101-961b-27ed5fa34a5b # QR Scan Table
fieldLayouts:
  61fd81df-aa3e-4f74-9a68-e4f062750e6f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b9cbf7cc-8594-4e02-abbe-0c17c35ef005 # Neurotransmitters
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9021127e-462d-4926-9bb5-f1137b8b13bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8b1dd37a-41df-402f-af40-ccbc41273def # Range
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccf48da3-786c-4e22-bc93-4b25d1fe3a5c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cd95af5f-59e3-44f1-ab1a-0c66d740d9b9 # Associated Product
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 747d160f-2699-4a73-b0c9-08630180e76e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 564c5e54-0206-4672-a25f-a9d52fce7d72 # Age
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a650a74-bac8-4bdd-bdaf-728f6b4a1d1a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0615a5a7-ecbf-4023-ad4f-602c6b1815b2 # Age Check
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ef35c60-6602-4209-a8b8-bb9fd133076f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 84ff1395-1a14-4763-9cc7-5ee23a880dcd # Immune/ Adrenal
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4423f82-f47d-4f4c-8258-fb46666f89ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1443ab41-a4dc-40a3-9de7-9b8a6e4d395c # Product Checks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba9a36fd-bd28-4dfa-9fa4-9e21551db796
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 352f6db0-4f86-4e06-bae7-63d61504e1a1 # end
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68684ec3-5d00-476c-9683-143687739728
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6701064a-c98f-475c-a542-ef71caf1516f
        userCondition: null
fields:
  8b1dd37a-41df-402f-af40-ccbc41273def: # Range
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: range
    instructions: null
    name: Range
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Low/Min
            -
              - value
              - lowMin
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Max/High
            -
              - value
              - maxHigh
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Low
            -
              - value
              - low
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Min
            -
              - value
              - min
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Max
            -
              - value
              - max
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - High
            -
              - value
              - high
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  84ff1395-1a14-4763-9cc7-5ee23a880dcd: # Immune/ Adrenal
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: immuneAdrenal
    instructions: null
    name: 'Immune/ Adrenal'
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Not specified'
            -
              - value
              - notSpecified
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Immune
            -
              - value
              - immune
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Adrenal
            -
              - value
              - adrenal
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  352f6db0-4f86-4e06-bae7-63d61504e1a1: # end
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: end
    instructions: null
    name: end
    searchable: true
    settings:
      errorMessage: 'Unable to find component class ''SuperTable_Label''.'
      expectedType: SuperTable_Label
      settings:
        __assoc__:
          -
            - value
            - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MissingField
  564c5e54-0206-4672-a25f-a9d52fce7d72: # Age
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: age
    instructions: null
    name: Age
    searchable: true
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - 'Not specified'
            -
              - value
              - notSpecified
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 13+
            -
              - value
              - '13'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 12-
            -
              - value
              - '12'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  0615a5a7-ecbf-4023-ad4f-602c6b1815b2: # Age Check
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: ageCheck
    instructions: null
    name: 'Age Check'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  1443ab41-a4dc-40a3-9de7-9b8a6e4d395c: # Product Checks
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: productChecks
    instructions: '(NOT been selected previously)'
    name: 'Product Checks'
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\commerce\fields\Products
  b9cbf7cc-8594-4e02-abbe-0c17c35ef005: # Neurotransmitters
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: neurotransmitters
    instructions: null
    name: Neurotransmitters
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: true
      maxRelations: null
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      source: 'group:f7a04aca-b458-463e-ac40-4e70fe38fe09' # QR Scan Pathways
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  cd95af5f-59e3-44f1-ab1a-0c66d740d9b9: # Associated Product
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: associatedProduct
    instructions: null
    name: 'Associated Product'
    searchable: true
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\commerce\fields\Products
