changedFieldIndicator: null
field: 3a205d9c-a63e-47ed-ad38-3bf91c604902 # Alert Message
fieldLayouts:
  f8585498-a2da-49d6-bcc1-1d97847ab6a0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 95f7cc27-b2bd-48d4-87e7-3f95f180aafd # Alert Message
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b3645a6-a3c0-41bc-bf66-04dfc6e45635
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8e4a8896-ce66-44a0-bc79-86bcb4efe033 # Alert CTA
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76c0a920-854f-43cb-b88b-ed3b2fba033c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 05bf280e-e841-40b5-b0bb-a19853338165 # Show Alert
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 567c7f51-6119-4546-a095-5470724c2703
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9a83950c-81cc-4b2a-8c5e-97a6c45ce7c5
        userCondition: null
fields:
  05bf280e-e841-40b5-b0bb-a19853338165: # Show Alert
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: showAlert
    instructions: null
    name: 'Show Alert'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  8e4a8896-ce66-44a0-bc79-86bcb4efe033: # Alert CTA
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: alertCta
    instructions: null
    name: 'Alert CTA'
    searchable: true
    settings:
      allowCustomText: true
      allowTarget: true
      defaultText: null
      selectLinkText: ''
      types:
        __assoc__:
          -
            - presseddigital\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - 1
          -
            - presseddigital\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - 1
          -
            - presseddigital\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - 1
          -
            - presseddigital\linkit\models\Entry
            -
              __assoc__:
                -
                  - enabled
                  - 1
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select an entry'
          -
            - presseddigital\linkit\models\Category
            -
              __assoc__:
                -
                  - enabled
                  - 1
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select a category'
          -
            - presseddigital\linkit\models\Asset
            -
              __assoc__:
                -
                  - enabled
                  - 1
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select an asset'
          -
            - presseddigital\linkit\models\Product
            -
              __assoc__:
                -
                  - enabled
                  - 1
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - 'Select an entry'
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\linkit\fields\LinkitField
  95f7cc27-b2bd-48d4-87e7-3f95f180aafd: # Alert Message
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: alertMessage
    instructions: null
    name: 'Alert Message'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 45ee12db-a387-4bf5-bf41-95d8744b1ffa # Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      showWordCount: false
      sourceEditingGroups: '*'
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
