changedFieldIndicator: null
field: 3a205d9c-a63e-47ed-ad38-3bf91c604902 # Alert Message
fieldLayouts:
  f8585498-a2da-49d6-bcc1-1d97847ab6a0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 95f7cc27-b2bd-48d4-87e7-3f95f180aafd # Alert Message
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83bf9196-4917-4e50-be6c-15980c0fd5c8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8e4a8896-ce66-44a0-bc79-86bcb4efe033 # Alert CTA
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4712521-ed9c-4996-9d54-639370c863db
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 05bf280e-e841-40b5-b0bb-a19853338165 # Show Alert
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f79679d-9734-43c1-8905-3d35038b95fb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 837c0c67-0895-4dab-ab21-2702028937f2
        userCondition: null
fields:
  05bf280e-e841-40b5-b0bb-a19853338165: # Show Alert
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: showAlert
    instructions: null
    name: 'Show Alert'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  8e4a8896-ce66-44a0-bc79-86bcb4efe033: # Alert CTA
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: alertCta
    instructions: null
    name: 'Alert CTA'
    searchable: true
    settings:
      allowCustomText: true
      allowTarget: true
      defaultText: null
      selectLinkText: ''
      types:
        __assoc__:
          -
            - presseddigital\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - 1
          -
            - presseddigital\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - 1
          -
            - presseddigital\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - 1
          -
            - presseddigital\linkit\models\Entry
            -
              __assoc__:
                0:
                  - enabled
                  - 1
                2:
                  - sources
                  - '*'
                3:
                  - customSelectionLabel
                  - 'Select an entry'
          -
            - presseddigital\linkit\models\Category
            -
              __assoc__:
                0:
                  - enabled
                  - 1
                2:
                  - sources
                  - '*'
                3:
                  - customSelectionLabel
                  - 'Select a category'
          -
            - presseddigital\linkit\models\Asset
            -
              __assoc__:
                0:
                  - enabled
                  - 1
                2:
                  - sources
                  - '*'
                3:
                  - customSelectionLabel
                  - 'Select an asset'
          -
            - presseddigital\linkit\models\Product
            -
              __assoc__:
                0:
                  - enabled
                  - 1
                2:
                  - sources
                  - '*'
                3:
                  - customSelectionLabel
                  - 'Select an entry'
    translationKeyFormat: null
    translationMethod: none
    type: presseddigital\linkit\fields\LinkitField
  95f7cc27-b2bd-48d4-87e7-3f95f180aafd: # Alert Message
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: alertMessage
    instructions: null
    name: 'Alert Message'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      ckeConfig: 3c7d8a91-2b4e-4f63-9c1d-8e5f6a7b9c0d # Standard
      columnType: text
      defaultTransform: ''
      enableSourceEditingForNonAdmins: true
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
