changedFieldIndicator: null
field: 9901899c-95b6-402f-ac0d-0b5709e44b9c # Education Materials
fieldLayouts:
  c16d8ef2-c6de-4ef1-b2d1-6b5bc686af4b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0d914fff-b4b8-42a3-b98d-77caaba8781d # Restricted Access?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c013ff9-8183-4760-9ee6-e6a2f86d7eff
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cabe8363-0383-4075-9726-56e6e2fe76af # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e963bbe8-19c1-4ee6-9992-41883e2a9abe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9ab250b7-b056-45ef-91cd-52918b0599bd # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfc04490-31fc-4e89-b420-44fc41845928
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbfc2c81-26c5-478c-a8a1-ad3429910c78 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84927169-2d59-4e43-bf7e-80bb07e6b13f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cf76daff-2c39-465f-8d83-9acd3b0d172b # Materials
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0875e73e-bf48-4062-bdd3-6a994ebd2a4a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ed70687a-ec3a-482b-aa3a-e6643ae25324 # Accordion Drawer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2514ddbf-3672-48fc-9d1b-36feb8c870ee
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6f3cd670-bf8f-45a1-951f-fe891cc7a8da
        userCondition: null
fields:
  0d914fff-b4b8-42a3-b98d-77caaba8781d: # Restricted Access?
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: restrictedAccess
    instructions: null
    name: 'Restricted Access?'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  9ab250b7-b056-45ef-91cd-52918b0599bd: # Color
    columnSuffix: null
    contentColumnType: char(7)
    fieldGroup: null
    handle: color
    instructions: null
    name: Color
    searchable: true
    settings:
      defaultColor: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  cabe8363-0383-4075-9726-56e6e2fe76af: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cbfc2c81-26c5-478c-a8a1-ad3429910c78: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: null
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      characterLimit: null
      ckeConfig: 45ee12db-a387-4bf5-bf41-95d8744b1ffa # Simple
      columnType: text
      defaultTransform: null
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      showWordCount: false
      sourceEditingGroups: '*'
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  cf76daff-2c39-465f-8d83-9acd3b0d172b: # Materials
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: materials
    instructions: null
    name: Materials
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_materials}}'
      maxBlocks: null
      minBlocks: null
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  ed70687a-ec3a-482b-aa3a-e6643ae25324: # Accordion Drawer
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: accordionDrawer
    instructions: null
    name: 'Accordion Drawer'
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_accordiondrawer}}'
      maxBlocks: null
      minBlocks: null
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
