changedFieldIndicator: null
field: 9901899c-95b6-402f-ac0d-0b5709e44b9c # Education Materials
fieldLayouts:
  c16d8ef2-c6de-4ef1-b2d1-6b5bc686af4b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0d914fff-b4b8-42a3-b98d-77caaba8781d # Restricted Access?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73b39a2f-f453-49a1-a50d-927fa669a6b6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cabe8363-0383-4075-9726-56e6e2fe76af # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a5e6166-b640-4ecb-80f2-c019986d3809
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9ab250b7-b056-45ef-91cd-52918b0599bd # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fda6dd8a-60e9-4f43-95b3-1f2dea6ec481
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cbfc2c81-26c5-478c-a8a1-ad3429910c78 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02f7aacd-2ff6-44fc-9774-49ec1328c6b6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cf76daff-2c39-465f-8d83-9acd3b0d172b # Materials
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2882f197-6b21-459f-9f11-cdac2d356908
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ed70687a-ec3a-482b-aa3a-e6643ae25324 # Accordion Drawer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7b5aff7-ca9d-4616-8085-41e314d26d69
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 013ab673-d959-4ffc-bf7f-fe10f8fda191
        userCondition: null
fields:
  0d914fff-b4b8-42a3-b98d-77caaba8781d: # Restricted Access?
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: restrictedAccess
    instructions: null
    name: 'Restricted Access?'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  9ab250b7-b056-45ef-91cd-52918b0599bd: # Color
    columnSuffix: null
    contentColumnType: char(7)
    fieldGroup: null
    handle: color
    instructions: null
    name: Color
    searchable: true
    settings:
      defaultColor: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  cabe8363-0383-4075-9726-56e6e2fe76af: # Headline
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: text
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cbfc2c81-26c5-478c-a8a1-ad3429910c78: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: null
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Standard.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  cf76daff-2c39-465f-8d83-9acd3b0d172b: # Materials
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: materials
    instructions: null
    name: Materials
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_materials}}'
      maxBlocks: null
      minBlocks: null
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  ed70687a-ec3a-482b-aa3a-e6643ae25324: # Accordion Drawer
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: accordionDrawer
    instructions: null
    name: 'Accordion Drawer'
    searchable: true
    settings:
      contentTable: '{{%matrixcontent_accordiondrawer}}'
      maxBlocks: null
      minBlocks: null
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
