fieldLayouts:
  ef414f8e-c22a-431f-be16-1ce4ecf96852:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5367bd89-34e8-4536-9dc6-4bfe8cbb6fe7 # Shipping Notification
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e525b30-5cd4-4792-89dc-a6714cdc7580
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 04a9ca8f-1f1b-4fe4-a0c6-071c4f1dc17b # New Account Note
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c966ed9c-100c-42f8-8cc8-a66feec74eb4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: af986110-9f12-431d-b653-7cf1ddcdd3a7 # Sales Rep Search
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0fb8869-ff08-4ddb-8aff-71a0def646be
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6d4cd5f1-16c3-42c3-a54e-64aac047d864 # Sales Rep Search Empty
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89a81004-de2f-42ae-86c5-44b84104fbfc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 19793459-73e0-400d-b5a6-ec42349e1cd2 # Must Be Registered
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e869c92-53ad-436a-bec4-4da41f3429c4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 63776c34-9e85-4c72-8f64-10a455c2ae68 # Patient fulfillment: Terms & Conditions
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 690cecd0-5602-4b2d-b630-fd5b37f00b2e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 84644c79-d095-41ea-ad87-f8a63d2a9f12
        userCondition: null
handle: generalTextNotifications
name: 'General Text Notifications'
sortOrder: 3
