fieldLayouts:
  50cd1481-b935-4994-b3cf-9eca0a1e125e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 37076289-5388-494c-ab16-50f8f15ef55d # HCP NeuroCash Percentage
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72833abf-ec64-42fd-8ea5-69db296d3303
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 84bbdaa0-4f51-45c4-87fc-da34da0bb16c # Free Shipping Mark
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2457945d-1618-46ba-bbb0-8c7a1c1d0bb2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bc1a584e-9391-460b-a62b-19c4c88bec4b # Chat Enabled
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9759a80b-6232-4c14-aa0c-a2034770fe9c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3a205d9c-a63e-47ed-ad38-3bf91c604902 # Alert Message
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88db96df-60af-4f51-a093-916a8f9c6223
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa19d720-9a33-4fb2-9371-3ca8cabc3cb9 # Phone Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f70fd8ff-3d70-4495-ab78-474e29d52170
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c600ba22-fc96-435d-9dee-28bea2237969 # Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3e04368-0ad6-493d-8d04-e0c163dfd291
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6155050f-240b-4ccc-9afc-095f7b936e55 # Social Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bec0257c-ef07-407f-85ef-923b3541a7ed
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4f5a97f7-34f5-4b71-8ccc-e7a53f72315d # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3e2abc1-9054-4ba7-a93b-86c0d08bb32a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f5e28e8c-7385-4979-9781-4073154127ad # References
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb63c8a8-59c0-4c0b-949f-037f6e3e38bd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4b922f32-6d51-42bf-b523-3cd43bd3b029
        userCondition: null
handle: globalObjects
name: 'Global Objects'
sortOrder: 4
