fieldLayouts:
  f84d96dc-f648-469a-ad9e-221bacfc402c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 57ec9101-664f-4658-a7b7-dfa7f120f024 # N0007 Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1dfbe5e0-60ab-4dc2-96cd-2eced27b965b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c1e3cfa-a11e-49cd-be1d-71571172959e # N0007 Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a46e2bfb-d319-4279-936b-1a823142d6c3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c4bffc59-89a5-48fa-b339-4283a5f28af2 # N0011 Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71e0c480-5693-4476-a8bf-4e7ca7ca81a3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a94acfe2-14f9-4830-a0cf-08f250c1c7d9 # N0011 Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ce706dd-b35c-43be-bcf0-4dacc0cd0ab9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b64f83ff-c496-41da-9dae-376b26f213b5 # N0003 Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f2e54f0-cf73-471f-be66-3c86ea91861d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7e4bb0c8-fee3-4856-9ddb-0912afe86208 # N0003 Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb5a5fe9-453c-470e-92bd-1ed1f9854efd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dc21dd8f-5a86-4183-906e-142c04a68a6f # Filter by Symptom Legal Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d30b83ef-4f16-47b9-9095-a3b80c2a3eb8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 054cb64c-3f11-4dac-8457-e4035a588d46
        userCondition: null
handle: legalDocuments
name: 'Legal Documents'
sortOrder: 5
