fieldLayouts:
  f84d96dc-f648-469a-ad9e-221bacfc402c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 57ec9101-664f-4658-a7b7-dfa7f120f024 # N0007 Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 236c7253-19c9-4fbd-994d-aeb3aaab5044
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c1e3cfa-a11e-49cd-be1d-71571172959e # N0007 Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e1244bc-771d-4a5b-b9af-a2067135d0cc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c4bffc59-89a5-48fa-b339-4283a5f28af2 # N0011 Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23e69d0e-c29e-47ed-9da4-05994fd76b8a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a94acfe2-14f9-4830-a0cf-08f250c1c7d9 # N0011 Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b490e41-5692-42a1-a731-6395ee4eb4e1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b64f83ff-c496-41da-9dae-376b26f213b5 # N0003 Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 603119eb-7946-4dd4-a967-da54bb5399f7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7e4bb0c8-fee3-4856-9ddb-0912afe86208 # N0003 Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6aab8b9a-ad5b-4de0-afa3-3928410ee452
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dc21dd8f-5a86-4183-906e-142c04a68a6f # Filter by Symptom Legal Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef74d68c-d346-4732-a7f0-c91b11f3babc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 054cb64c-3f11-4dac-8457-e4035a588d46
        userCondition: null
handle: legalDocuments
name: 'Legal Documents'
sortOrder: 5
