fieldLayouts:
  f2cce011-b7b2-41ea-aaad-d6953a666bcd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 693887d6-503f-479e-b676-b2f548ab5367 # Pathways Table
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9768191b-4d0e-4412-b9e6-cae26fb279ef
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fc97a80f-67d7-4319-9b05-fd050f58fa5e
        userCondition: null
handle: pathwaysTable
name: 'Pathways Table'
sortOrder: 6
