description: null
handle: superAdmin
name: 'Super Admin'
permissions:
  - accesscp
  - accesscpwhensystemisoff
  - accessplugin-commerce
  - accessplugin-seomatic
  - accesssitewhensystemisoff
  - administrateusers
  - 'assignusergroup:51e7da1c-9888-4197-a25e-c456eebf2312' # Health Care Professionals
  - 'assignusergroup:7bb97651-ed90-45bb-b144-6bcac199bfa8' # NeuroSelect Only
  - 'assignusergroup:b0d5543d-a8fb-481b-9727-8bdb7d52f9dc' # Customer Service
  - 'assignusergroup:e0e6611c-ec20-44b8-96ce-23e0fa0d253b' # Personal (PUP)
  - assignuserpermissions
  - commerce-capturepayment
  - commerce-creatediscounts
  - 'commerce-createproducts:3593d06b-3003-4322-809a-7cfbf14d11eb' # Standard
  - commerce-createsales
  - commerce-deletediscounts
  - commerce-deleteorders
  - 'commerce-deleteproducts:3593d06b-3003-4322-809a-7cfbf14d11eb' # Standard
  - commerce-deletesales
  - commerce-editdiscounts
  - commerce-editorders
  - 'commerce-editproducttype:3593d06b-3003-4322-809a-7cfbf14d11eb' # Standard
  - commerce-editsales
  - commerce-manageorders
  - commerce-managepromotions
  - commerce-manageshipping
  - commerce-managestoresettings
  - commerce-managesubscriptions
  - commerce-managetaxes
  - commerce-refundpayment
  - 'createentries:6c1630f3-e220-4731-8275-a2f31e2bda2d' # News
  - 'createentries:a7d38fe9-86e0-495c-9bca-a8567b4a1159' # Healthcare Providers
  - 'createentries:bad38a62-ef16-4379-8cba-0e7dfbab754f' # Pages
  - 'createentries:cf21ce66-449e-4403-a1c7-77f684812ccb' # Patients
  - 'createfoldersinvolume:7d8fed8f-0af5-4e9f-bde0-eb2d76ddf7dd' # User Photos
  - 'createfoldersinvolume:a2ea3e3f-97b8-4daf-9166-ebb4176fcf16' # Sales Reps
  - 'deleteentries:6c1630f3-e220-4731-8275-a2f31e2bda2d' # News
  - 'deleteentries:a7d38fe9-86e0-495c-9bca-a8567b4a1159' # Healthcare Providers
  - 'deleteentries:bad38a62-ef16-4379-8cba-0e7dfbab754f' # Pages
  - 'deleteentries:cf21ce66-449e-4403-a1c7-77f684812ccb' # Patients
  - 'deletefilesandfoldersinvolume:7d8fed8f-0af5-4e9f-bde0-eb2d76ddf7dd' # User Photos
  - 'deletefilesandfoldersinvolume:a2ea3e3f-97b8-4daf-9166-ebb4176fcf16' # Sales Reps
  - 'deletepeerentries:6c1630f3-e220-4731-8275-a2f31e2bda2d' # News
  - 'deletepeerentries:a7d38fe9-86e0-495c-9bca-a8567b4a1159' # Healthcare Providers
  - 'deletepeerentries:bad38a62-ef16-4379-8cba-0e7dfbab754f' # Pages
  - 'deletepeerentries:cf21ce66-449e-4403-a1c7-77f684812ccb' # Patients
  - 'deletepeerentrydrafts:073663c2-4a85-4e07-b664-2b220dc71ad5' # Register
  - 'deletepeerentrydrafts:1c9dfb1e-4bf8-4adc-9a57-3dc824575af5' # FAQ
  - 'deletepeerentrydrafts:51f315e9-0e39-4e97-a846-073605f7e9bf' # Healthcare Providers Overview
  - 'deletepeerentrydrafts:63dbe529-4121-4b5c-861e-eb57f018bbf7' # Contact
  - 'deletepeerentrydrafts:6c1630f3-e220-4731-8275-a2f31e2bda2d' # News
  - 'deletepeerentrydrafts:84f8f7cb-8c2a-4fe3-9ea8-f946141a4483' # Patients Overview
  - 'deletepeerentrydrafts:a7d38fe9-86e0-495c-9bca-a8567b4a1159' # Healthcare Providers
  - 'deletepeerentrydrafts:b5b15287-8bfd-4df9-b271-06ed382fb53d' # Login
  - 'deletepeerentrydrafts:b5b225c2-9b91-44ab-95f4-c9ec2af5ed6e' # About
  - 'deletepeerentrydrafts:bad38a62-ef16-4379-8cba-0e7dfbab754f' # Pages
  - 'deletepeerentrydrafts:cb37c8c8-928f-4175-946a-5cbecc60c2f2' # Products Landing
  - 'deletepeerentrydrafts:cc788334-996f-492a-948f-c70687deaeb2' # Reset Password
  - 'deletepeerentrydrafts:cf21ce66-449e-4403-a1c7-77f684812ccb' # Patients
  - 'deletepeerentrydrafts:e011d030-7864-4189-9080-75b764853710' # Personal Use Purchasing Register
  - 'deletepeerentrydrafts:e2114991-fe88-4d06-b236-dda841abc628' # Homepage
  - 'deletepeerentrydrafts:e3272832-0ed6-494f-8e33-8e30afdaed2a' # Sleep Promo
  - 'deletepeerfilesinvolume:7d8fed8f-0af5-4e9f-bde0-eb2d76ddf7dd' # User Photos
  - 'deletepeerfilesinvolume:a2ea3e3f-97b8-4daf-9166-ebb4176fcf16' # Sales Reps
  - deleteusers
  - 'editglobalset:03ce674d-8ec5-4ca5-9416-ada9c81df133' # Pathways Table
  - 'editglobalset:14aa199d-d6e5-4452-bcaf-883d2715be11' # Legal Documents
  - 'editglobalset:243467cc-4483-401c-abd4-a704876f5960' # Global Objects
  - 'editglobalset:26f26b9c-4d84-4b20-bb60-2bcef6530d47' # Clinical Indicators Table
  - 'editglobalset:45718c3c-283b-450e-9596-a3c7c3d6a997' # Sleep Table
  - 'editglobalset:8df44416-3efd-4db4-ab88-7d436d62d9bf' # General Text Notifications
  - 'editglobalset:ba3ec8b7-7ff0-4aff-9c1b-bccc3843068a' # Updated Pathways Table
  - 'editglobalset:f634c74c-ffa3-443c-9eda-bd18b55092b8' # QR Scan Table
  - 'editimagesinvolume:7d8fed8f-0af5-4e9f-bde0-eb2d76ddf7dd' # User Photos
  - 'editimagesinvolume:a2ea3e3f-97b8-4daf-9166-ebb4176fcf16' # Sales Reps
  - 'editpeerfilesinvolume:7d8fed8f-0af5-4e9f-bde0-eb2d76ddf7dd' # User Photos
  - 'editpeerfilesinvolume:a2ea3e3f-97b8-4daf-9166-ebb4176fcf16' # Sales Reps
  - 'editpeerimagesinvolume:7d8fed8f-0af5-4e9f-bde0-eb2d76ddf7dd' # User Photos
  - 'editpeerimagesinvolume:a2ea3e3f-97b8-4daf-9166-ebb4176fcf16' # Sales Reps
  - editusers
  - impersonateusers
  - moderateusers
  - performupdates
  - registerusers
  - 'replacepeerfilesinvolume:7d8fed8f-0af5-4e9f-bde0-eb2d76ddf7dd' # User Photos
  - 'replacepeerfilesinvolume:a2ea3e3f-97b8-4daf-9166-ebb4176fcf16' # Sales Reps
  - 'saveassetinvolume:7d8fed8f-0af5-4e9f-bde0-eb2d76ddf7dd' # User Photos
  - 'saveassetinvolume:a2ea3e3f-97b8-4daf-9166-ebb4176fcf16' # Sales Reps
  - 'seomatic:content-meta'
  - 'seomatic:content-meta:facebook'
  - 'seomatic:content-meta:general'
  - 'seomatic:content-meta:sitemap'
  - 'seomatic:content-meta:twitter'
  - 'seomatic:dashboard'
  - 'seomatic:global-meta'
  - 'seomatic:global-meta:ads'
  - 'seomatic:global-meta:facebook'
  - 'seomatic:global-meta:general'
  - 'seomatic:global-meta:humans'
  - 'seomatic:global-meta:robots'
  - 'seomatic:global-meta:twitter'
  - 'seomatic:plugin-settings'
  - 'seomatic:site-settings'
  - 'seomatic:site-settings:creator'
  - 'seomatic:site-settings:identity'
  - 'seomatic:site-settings:miscellaneous'
  - 'seomatic:site-settings:sitemap'
  - 'seomatic:site-settings:social'
  - 'seomatic:tracking-scripts'
  - 'seomatic:tracking-scripts:facebookpixel'
  - 'seomatic:tracking-scripts:googleanalytics'
  - 'seomatic:tracking-scripts:googletagmanager'
  - 'seomatic:tracking-scripts:gtag'
  - 'seomatic:tracking-scripts:hubspot'
  - 'seomatic:tracking-scripts:linkedininsight'
  - 'utility:asset-indexes'
  - 'utility:clear-caches'
  - 'utility:db-backup'
  - 'utility:deprecation-errors'
  - 'utility:find-replace'
  - 'utility:migrations'
  - 'utility:php-info'
  - 'utility:queue-manager'
  - 'utility:system-messages'
  - 'utility:system-report'
  - 'utility:updates'
  - 'viewpeerfilesinvolume:7d8fed8f-0af5-4e9f-bde0-eb2d76ddf7dd' # User Photos
  - 'viewpeerfilesinvolume:a2ea3e3f-97b8-4daf-9166-ebb4176fcf16' # Sales Reps
  - 'viewvolume:7d8fed8f-0af5-4e9f-bde0-eb2d76ddf7dd' # User Photos
  - 'viewvolume:a2ea3e3f-97b8-4daf-9166-ebb4176fcf16' # Sales Reps
