defaultPlacement: end
enableVersioning: true
handle: patientsOverview
name: 'Patients Overview'
previewTargets:
  -
    __assoc__:
      -
        - label
        - Primary
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  9980c1bd-fa51-4b79-b81f-bf4576d54b1e: # NeuroScience
    enabledByDefault: true
    hasUrls: true
    template: patients/index
    uriFormat: patients
type: single
