defaultPlacement: end
enableVersioning: true
handle: sleepPromo
name: 'Sleep Promo'
previewTargets:
  -
    __assoc__:
      -
        - label
        - Primary
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  9980c1bd-fa51-4b79-b81f-bf4576d54b1e: # NeuroScience
    enabledByDefault: true
    hasUrls: true
    template: pages/_promo.html
    uriFormat: sleep-promo
type: single
