tabs:
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\commerce\fieldlayoutelements\UserAddressSettings
        uid: 6d87d3e4-535f-4f16-b70b-fc3ed5a14b82
        userCondition: null
        warning: null
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 0e7c749c-ae29-4b0c-b352-45f07d187665
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        elementCondition: null
        id: null
        instructions: null
        label: null
        orientation: null
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: a610801e-bf79-4c69-a3c7-bf6f83ca6a7c
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 6d0c6f1c-0d84-49bc-b7a9-62907685a1fb
        userCondition: null
        warning: null
      -
        elementCondition: null
        fieldUid: 5e117cad-bb4f-42d5-8e50-4f787f128637 # Attention
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 5968d653-c921-488d-a4f9-fa1852f66509
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: dea345ea-f53c-463d-b0cc-7eb1eb5f76f3 # Phone Number
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: b2276fff-c524-405d-88cb-c962917738cb
        userCondition: null
        warning: null
        width: 100
      -
        attribute: fullName
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        requirable: true
        required: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\FullNameField
        uid: 15e152f9-6cd9-49d5-b0ff-4315f4f31275
        userCondition: null
        warning: null
        width: 100
      -
        attribute: organization
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        requirable: true
        required: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\OrganizationField
        uid: dad40e45-5352-4451-85ec-90618fde9cdd
        userCondition: null
        warning: null
        width: 100
    name: Content
    uid: ddf63961-edac-4aa5-ab57-84fcbd7b67cd
    userCondition: null
