tabs:
  -
    elementCondition: null
    elements:
      -
        elementCondition: null
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\commerce\fieldlayoutelements\UserAddressSettings
        uid: d4214c3d-86d2-4090-92cd-d87f55489b53
        userCondition: null
        warning: null
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 67c34128-785c-4a77-880b-cc0df67b0222
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        elementCondition: null
        id: null
        instructions: null
        label: null
        orientation: null
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: 22365bbd-4d0d-4975-9e7c-93f507626e39
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 78cedde0-f3ed-4abf-8534-7dd88d76b17a
        userCondition: null
        warning: null
      -
        elementCondition: null
        fieldUid: b3bca242-9def-4d67-acae-974b7e4148f1 # Attention
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: c090b64d-0b3f-484b-82d8-9018f9a9e5d9
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        fieldUid: 3b3253b6-ecf7-4883-8cf0-ff7f386d533b # Phone Number
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: f026be03-3558-46bd-b68e-e0fd220738e4
        userCondition: null
        warning: null
        width: 100
      -
        attribute: fullName
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        requirable: true
        required: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\FullNameField
        uid: 4428970b-498b-4272-88e9-6733622126cf
        userCondition: null
        warning: null
        width: 100
      -
        attribute: organization
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        requirable: true
        required: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\OrganizationField
        uid: 8fa5b7be-9fbf-4b6d-97e9-edadd8d8a7f3
        userCondition: null
        warning: null
        width: 100
    name: Content
    uid: ae52b62c-0adc-4d72-bd51-5c3fc36228ca
    userCondition: null
